# Upper/lower limb sets from Sobotta 1909 plates; positions = label centers in % (from OCR blocks or read from originals)
T={
 'tub_costae':('Tuberculum costae','Горбок ребра'),'caput_costae':('Caput costae','Головка ребра'),'tub_scal':('Tuberculum musculi scaleni anterioris','Горбок переднього драбинчастого м’яза'),
 's_subclav':('Sulcus arteriae subclaviae','Борозна підключичної артерії'),'collum_costae':('Collum costae','Шийка ребра'),'tub_serr':('Tuberositas musculi serrati anterioris','Горбистість переднього зубчастого м’яза'),
 'cr_colli':('Crista colli costae','Гребінь шийки ребра'),'ang_costae':('Angulus costae','Кут ребра'),'fac_tub_costae':('Facies articularis tuberculi costae','Суглобова поверхня горбка ребра'),
 'cr_cap_costae':('Crista capitis costae','Гребінь головки ребра'),'fac_cap_costae':('Facies articularis capitis costae','Суглобова поверхня головки ребра'),
 's_costae':('Sulcus costae','Реброва борозна'),'corpus_costae':('Corpus costae','Тіло ребра'),
 'vc6':('Vertebra cervicalis VI','Шостий шийний хребець'),'vc7':('Vertebra cervicalis VII','Сьомий шийний хребець'),'clavicula':('Clavicula','Ключиця'),
 'vt1':('Vertebra thoracica I','Перший грудний хребець'),'vt12':('Vertebra thoracica XII','Дванадцятий грудний хребець'),'vl1':('Vertebra lumbalis I','Перший поперековий хребець'),
 'costa1':('Costa I','Перше ребро'),'costa2':('Costa II','Друге ребро'),'costa4':('Costa IV','Четверте ребро'),'costa6':('Costa VI','Шосте ребро'),'costa7':('Costa VII','Сьоме ребро'),
 'costa11':('Costa XI','Одинадцяте ребро'),'costa12':('Costa XII','Дванадцяте ребро'),'scapula':('Scapula','Лопатка'),'humerus':('Humerus','Плечова кістка'),
 'os_ilium':('Os ilium','Клубова кістка'),'femur':('Femur','Стегнова кістка'),'os_cocc':('Os coccygis','Куприк'),'os_sacrum':('Os sacrum','Крижова кістка'),
 'symph_pub':('Symphysis pubica','Лобковий симфіз'),

 'inc_jug':('Incisura jugularis','Яремна вирізка'),'inc_clav':('Incisura clavicularis','Ключична вирізка'),'inc_c1':('Incisura costalis I','Реброва вирізка I'),
 'inc_c2':('Incisura costalis II','Реброва вирізка II'),'inc_c3':('Incisura costalis III','Реброва вирізка III'),'inc_c4':('Incisura costalis IV','Реброва вирізка IV'),
 'inc_c5':('Incisura costalis V','Реброва вирізка V'),'inc_c6':('Incisura costalis VI','Реброва вирізка VI'),'inc_c7':('Incisura costalis VII','Реброва вирізка VII'),
 'manubrium':('Manubrium sterni','Рукоятка груднини'),'corpus_st':('Corpus sterni','Тіло груднини'),'xiph':('Processus xiphoideus','Мечоподібний відросток'),

 'sinus_tarsi':('Sinus tarsi','Пазуха заплесна'),'navic':('Os naviculare','Човноподібна кістка'),'talus':('Talus','Надп’яткова кістка'),
 'troch_peron':('Trochlea peronealis calcanei','Малогомілковий блок п’яткової кістки'),
 'caput_tali_nav':('Caput tali (facies articularis navicularis)','Головка надп’яткової кістки (човноподібна суглобова поверхня)'),
 'fac_calc_ant':('Facies articularis calcanea anterior','Передня п’яткова суглобова поверхня'),'fac_calc_med':('Facies articularis calcanea media','Середня п’яткова суглобова поверхня'),
 'sulcus_tali':('Sulcus tali','Борозна надп’яткової кістки'),'fac_calc_post':('Facies articularis calcanea posterior','Задня п’яткова суглобова поверхня'),
 's_fhl':('Sulcus tendinis musculi flexoris hallucis longi','Борозна сухожилка довгого м’яза-згинача великого пальця'),'proc_post_tali':('Processus posterior tali','Задній відросток надп’яткової кістки'),
 'proc_post_tali_med':('Processus posterior tali (tuberculum mediale)','Задній відросток надп’яткової кістки (присередній горбок)'),
 'corpus_tali':('Corpus tali','Тіло надп’яткової кістки'),'collum_tali':('Collum tali','Шийка надп’яткової кістки'),'fac_nav':('Facies articularis navicularis','Човноподібна суглобова поверхня'),

 'area_ic_ant':('Area intercondylaris anterior','Переднє міжвиросткове поле'),'tub_tib':('Tuberositas tibiae','Горбистість великогомілкової кістки'),
 'cond_med_t':('Condylus medialis tibiae','Присередній виросток великогомілкової кістки'),'cond_lat_t':('Condylus lateralis tibiae','Бічний виросток великогомілкової кістки'),
 'caput_fib':('Caput fibulae','Головка малогомілкової кістки'),'fac_cap_fib':('Facies articularis capitis fibulae','Суглобова поверхня головки малогомілкової кістки'),
 'apex_fib':('Apex capitis fibulae','Верхівка головки малогомілкової кістки'),'tub_ic_med':('Tuberculum intercondylare mediale','Присередній міжвиростковий горбок'),
 'area_ic_post':('Area intercondylaris posterior','Заднє міжвиросткове поле'),'tub_ic_lat':('Tuberculum intercondylare laterale','Бічний міжвиростковий горбок'),
 'mall_med':('Malleolus medialis','Присередня кісточка'),'fac_mall_lat':('Facies articularis malleoli lateralis','Суглобова поверхня бічної кісточки'),
 'mall_lat':('Malleolus lateralis','Бічна кісточка'),'fac_mall_med':('Facies articularis malleoli medialis','Суглобова поверхня присередньої кісточки'),
 'fac_inf_tib':('Facies articularis inferior tibiae','Нижня суглобова поверхня великогомілкової кістки'),
 'phal_hal':('Phalanges hallucis','Фаланги великого пальця стопи'),'phalanges_p':('Phalanges','Фаланги'),'sesam':('Ossa sesamoidea','Сесамоподібні кістки'),
 'metatarsus':('Metatarsus','Плесно'),'bases_mt':('Bases ossium metatarsalium','Основи плеснових кісток'),'tub_mt1':('Tuberositas ossis metatarsalis I','Горбистість I плеснової кістки'),
 'tub_mt5':('Tuberositas ossis metatarsalis V','Горбистість V плеснової кістки'),'cun_med':('Os cuneiforme mediale','Присередня клиноподібна кістка'),
 's_peron':('Sulcus tendinis musculi peronei longi','Борозна сухожилка довгого малогомілкового м’яза'),'cun_int':('Os cuneiforme intermedium','Проміжна клиноподібна кістка'),
 'tub_cub':('Tuberositas ossis cuboidei','Горбистість кубоподібної кістки'),'tub_nav':('Tuberositas ossis navicularis','Горбистість човноподібної кістки'),
 'cun_lat':('Os cuneiforme laterale','Бічна клиноподібна кістка'),'tarsus':('Tarsus','Заплесно'),'caput_tali':('Caput tali','Головка надп’яткової кістки'),
 'sustent':('Sustentaculum tali','Підпора надп’яткової кістки'),'proc_lat_calc':('Processus lateralis tuberis calcanei','Бічний відросток горба п’яткової кістки'),
 'proc_med_calc':('Processus medialis tuberis calcanei','Присередній відросток горба п’яткової кістки'),
 'ph3_d2':('Phalanx distalis digiti II','Дистальна фаланга II пальця'),'ph2_d2':('Phalanx media digiti II','Середня фаланга II пальця'),'ph1_d2':('Phalanx proximalis digiti II','Проксимальна фаланга II пальця'),
 'capita_mt':('Capita ossium metatarsalium','Головки плеснових кісток'),'cuboid':('Os cuboideum','Кубоподібна кістка'),'troch_tali':('Trochlea tali','Блок надп’яткової кістки'),
 'proc_lat_tali':('Processus lateralis tali','Бічний відросток надп’яткової кістки'),'calcaneus':('Calcaneus','П’яткова кістка'),

 'caput_f':('Caput femoris','Головка стегнової кістки'),'troch_maj':('Trochanter major','Великий вертлюг'),'collum_f':('Collum femoris','Шийка стегнової кістки'),
 'troch_min':('Trochanter minor','Малий вертлюг'),'lin_pect':('Linea pectinea','Гребінчаста лінія'),'lab_med_la':('Labium mediale lineae asperae','Присередня губа шорсткої лінії'),
 'lab_lat_la':('Labium laterale lineae asperae','Бічна губа шорсткої лінії'),'f_popl':('Facies poplitea','Підколінна поверхня'),
 'cond_lat':('Condylus lateralis','Бічний виросток'),'cond_med':('Condylus medialis','Присередній виросток'),'f_intercond':('Fossa intercondylaris','Міжвиросткова ямка'),
 'lin_intercond':('Linea intercondylaris','Міжвиросткова лінія'),'fovea_f':('Fovea capitis femoris','Ямка головки стегнової кістки'),'f_troch':('Fossa trochanterica','Вертлюгова ямка'),
 'lin_asp':('Linea aspera','Шорстка лінія'),'lin_intertroch':('Linea intertrochanterica','Міжвертлюгова лінія'),'cr_intertroch':('Crista intertrochanterica','Міжвертлюговий гребінь'),
 'tub_glut':('Tuberositas glutea','Сіднична горбистість'),'f_patel':('Facies patellaris','Наколінкова поверхня'),

 'lab_int':('Labium internum cristae iliacae','Внутрішня губа клубового гребеня'),'lin_interm':('Linea intermedia cristae iliacae','Проміжна лінія клубового гребеня'),'lab_ext':('Labium externum cristae iliacae','Зовнішня губа клубового гребеня'),
 'crista_il':('Crista iliaca','Клубовий гребінь'),'ala_il':('Ala ossis ilii','Крило клубової кістки'),'lg_post':('Linea glutea posterior','Задня сіднична лінія'),
 'sips':('Spina iliaca posterior superior','Верхня задня клубова ость'),'sias':('Spina iliaca anterior superior','Верхня передня клубова ость'),'corp_il':('Corpus ossis ilii','Тіло клубової кістки'),
 'sipi':('Spina iliaca posterior inferior','Нижня задня клубова ость'),'siai':('Spina iliaca anterior inferior','Нижня передня клубова ость'),'lg_ant':('Linea glutea anterior','Передня сіднична лінія'),
 'inc_isch_maj':('Incisura ischiadica major','Велика сіднича вирізка'),'lg_inf':('Linea glutea inferior','Нижня сіднична лінія'),'f_lunata':('Facies lunata','Півмісяцева поверхня'),
 'f_acet':('Fossa acetabuli','Ямка кульшової западини'),'cr_obt':('Crista obturatoria','Затульний гребінь'),'pecten':('Pecten ossis pubis','Гребінь лобкової кістки'),
 'spina_isch':('Spina ischiadica','Сіднича ость'),'inc_isch_min':('Incisura ischiadica minor','Мала сіднича вирізка'),'tub_pub':('Tuberculum pubicum','Лобковий горбок'),
 'tuber_isch':('Tuber ischiadicum','Сідничий горб'),'s_paragl':('Sulcus paraglenoidalis','Парагленоїдна борозна'),'tub_il':('Tuberositas iliaca','Клубова горбистість'),
 'f_auric':('Facies auricularis','Вушкоподібна поверхня'),'lin_arc':('Linea arcuata','Дугоподібна лінія'),'tub_obt_post':('Tuberculum obturatorium posterius','Задній затульний горбок'),
 's_obt':('Sulcus obturatorius','Затульна борозна'),'tub_obt_ant':('Tuberculum obturatorium anterius','Передній затульний горбок'),'f_symph':('Facies symphysialis','Симфізна поверхня'),
 'em_iliopub':('Eminentia iliopubica','Клубово-лобкове підвищення'),'corp_pub':('Corpus ossis pubis','Тіло лобкової кістки'),'acetab':('Acetabulum (facies lunata)','Кульшова западина (півмісяцева поверхня)'),
 'r_sup_pub':('Ramus superior ossis pubis','Верхня гілка лобкової кістки'),'corp_isch':('Corpus ossis ischii','Тіло сідничої кістки'),'r_sup_isch':('Ramus superior ossis ischii','Верхня гілка сідничої кістки'),
 'r_inf_pub':('Ramus inferior ossis pubis','Нижня гілка лобкової кістки'),'r_inf_isch':('Ramus inferior ossis ischii','Нижня гілка сідничої кістки'),

 'caput_r':('Caput radii','Головка променевої кістки'),'collum_r':('Collum radii','Шийка променевої кістки'),'tub_r':('Tuberositas radii','Горбистість променевої кістки'),
 'm_inteross':('Margo interosseus','Міжкістковий край'),'m_ant':('Margo anterior','Передній край'),'f_ant':('Facies anterior','Передня поверхня'),
 'styl_r':('Processus styloideus radii','Шилоподібний відросток променевої кістки'),'circ_r':('Circumferentia articularis','Суглобовий обвід'),
 'f_post_r':('Facies posterior','Задня поверхня'),'inc_uln':('Incisura ulnaris','Ліктьова вирізка'),'f_carp':('Facies articularis carpalis','Зап’ясткова суглобова поверхня'),
 'corpus_r':('Corpus radii','Тіло променевої кістки'),'m_post':('Margo posterior','Задній край'),'f_lat':('Facies lateralis','Бічна поверхня'),
 'olecr':('Olecranon','Ліктьовий відросток'),'fovea_r':('Fovea articularis capitis radii','Суглобова ямка головки променевої кістки'),'inc_troch':('Incisura trochlearis','Блокова вирізка'),
 'Ulna':('Ulna','Ліктьова кістка'),'Radius':('Radius','Променева кістка'),'styl_u':('Processus styloideus ulnae','Шилоподібний відросток ліктьової кістки'),

 'ang_sup':('Angulus superior','Верхній кут лопатки'),'inc_scap':('Incisura scapulae','Вирізка лопатки'),'m_sup':('Margo superior','Верхній край'),
 'coracoid':('Processus coracoideus','Дзьобоподібний відросток'),'spina':('Spina scapulae','Ость лопатки'),'acromion':('Acromion','Надплечовий відросток (акроміон)'),
 'glenoid':('Cavitas glenoidalis','Суглобова западина'),'m_med':('Margo medialis','Присередній (хребтовий) край'),'ang_lat':('Angulus lateralis','Бічний кут'),
 'collum_sc':('Collum scapulae','Шийка лопатки'),'m_lat':('Margo lateralis','Бічний (пахвовий) край'),'ang_inf':('Angulus inferior','Нижній кут'),
 'fac_acr':('Facies articularis acromii','Суглобова поверхня акроміона'),'f_subsc':('Fossa subscapularis','Підлопаткова ямка'),'lin_musc':('Lineae musculares','М’язові лінії'),
 'caput_h':('Caput humeri','Головка плечової кістки'),'tub_maj':('Tuberculum majus','Великий горбок'),'ext_prox':('Extremitas proximalis','Проксимальний кінець'),
 'col_chir':('Collum chirurgicum','Хірургічна шийка'),'corpus_h':('Corpus humeri','Тіло плечової кістки'),'s_rad':('Sulcus nervi radialis','Борозна променевого нерва'),
 'f_post':('Facies posterior','Задня поверхня'),'ext_dist':('Extremitas distalis','Дистальний кінець'),'f_olecr':('Fossa olecrani','Ліктьова ямка'),
 'epi_med':('Epicondylus medialis','Присередній надвиросток'),'epi_lat':('Epicondylus lateralis','Бічний надвиросток'),'trochlea_h':('Trochlea humeri','Блок плечової кістки'),
 's_uln':('Sulcus nervi ulnaris','Борозна ліктьового нерва'),'col_anat':('Collum anatomicum','Анатомічна шийка'),'s_intertub':('Sulcus intertubercularis','Міжгорбкова борозна'),
 'tub_min':('Tuberculum minus','Малий горбок'),'cr_maj':('Crista tuberculi majoris','Гребінь великого горбка'),'cr_min':('Crista tuberculi minoris','Гребінь малого горбка'),
 'tub_delt':('Tuberositas deltoidea','Дельтоподібна горбистість'),'for_nutr':('Foramen nutricium','Живильний отвір'),'mh_lat':('Margo lateralis','Бічний край'),
 'mh_med':('Margo medialis','Присередній край'),'f_antlat':('Facies anterolateralis','Передньобічна поверхня'),'f_antmed':('Facies anteromedialis','Передньоприсередня поверхня'),
 'f_coron':('Fossa coronoidea','Вінцева ямка'),'f_rad':('Fossa radialis','Променева ямка'),'capitulum':('Capitulum humeri','Головочка плечової кістки'),
}
SETS=[
 ('th-24','Перше ребро, зверху','Скелет',[('tub_costae',10.2,14.7),('caput_costae',29.3,21.6),('tub_scal',49.2,14.7),('s_subclav',57.6,37.8)]),
 ('th-25','Друге ребро, зверху','Скелет',[('collum_costae',6.9,79.9),('tub_costae',10.8,89.4),('tub_serr',89.9,83.7)]),
 ('th-26','Ребро, задня поверхня','Скелет',[('cr_colli',86.3,35.8),('ang_costae',34.9,63.4),('caput_costae',93.3,66.1),('fac_tub_costae',52.5,74.9)]),
 ('th-27','Ребро, вигляд зверху і зсередини','Скелет',[('cr_colli',23.7,8.5),('cr_cap_costae',69.7,12.5),('tub_costae',21.7,21.0),('fac_cap_costae',75.9,21.0),('collum_costae',43.7,43.0),('s_costae',45.4,55.1),('corpus_costae',46.7,63.1)]),
 ('th-28','Ребро, внутрішня поверхня','Скелет',[('caput_costae',15.3,13.1),('tub_costae',6.8,37.0),('collum_costae',27.5,40.6),('s_costae',25.8,50.8),('ang_costae',8.5,76.2),('corpus_costae',65.3,85.6)]),
 ('th-33','Грудна клітка, вигляд ззаду','Скелет',[('vc6',80.1,4.0),('clavicula',19.7,7.0),('vt1',85.1,8.3),('costa1',83.7,11.0),('costa2',90.1,14.5),('acromion',7.3,23.3),('scapula',7.3,27.3),('costa11',14.3,72.5),('costa12',18.3,76.3),('vl1',30.0,78.8),('vt12',76.7,78.0)]),
 ('th-34','Грудна клітка, вигляд спереду','Скелет',[('vc6',63.6,4.5),('costa1',19.6,11.5),('vt1',61.7,11.3),('clavicula',77.9,11.3),('acromion',90.2,11.3),('costa2',12.7,17.3),('coracoid',93.1,25.0),('glenoid',93.1,31.8),('costa4',89.3,39.5),('costa6',90.2,54.3),('costa7',91.2,61.8),('costa12',24.1,86.5),('vl1',59.2,87.5),('vt12',80.7,89.0),('costa11',8.2,91.5)]),
 ('th-35','Тулуб, вигляд збоку (з лопаткою і тазом)','Скелет',[('clavicula',39.1,5.8),('vc7',80.2,7.0),('vt1',82.2,10.3),('humerus',19.5,14.5),('scapula',81.7,16.5),('costa2',19.0,19.5),('costa11',15.5,52.8),('costa12',29.6,54.3),('vl1',24.5,56.3),('os_ilium',19.0,75.0),('femur',18.5,89.3),('os_cocc',63.1,92.0),('os_sacrum',73.6,92.0),('tuber_isch',62.1,94.8)]),
 ('th-36','Тулуб, вигляд збоку (сагітальний розпил хребта)','Скелет',[('vc7',70.3,8.0),('clavicula',77.8,11.8),('manubrium',85.9,18.0),('costa11',75.1,54.8),('costa12',69.2,57.0),('vl1',72.4,60.8),('sias',82.2,73.0),('os_sacrum',9.7,91.8),('symph_pub',74.1,91.8),('spina_isch',27.0,96.8)]),

 ('th-31','Груднина, передня поверхня','Скелет',[('inc_jug',48.5,5.2),('inc_clav',15.5,9.6),('inc_c1',15.5,21.3),('manubrium',81.4,27.3),('inc_c2',20.1,33.3),('inc_c3',17.0,48.3),('inc_c4',15.9,61.1),('corpus_st',82.6,60.3),('inc_c5',15.9,72.2),('inc_c6',16.3,78.5),('inc_c7',18.9,85.2),('xiph',75.0,89.4)]),
 ('th-32','Груднина, бічна поверхня','Скелет',[('inc_clav',63.0,7.1),('inc_c1',65.1,15.6),('manubrium',54.6,20.4),('inc_c2',60.9,27.8),('inc_c3',59.3,45.6),('corpus_st',59.3,52.7),('inc_c4',57.8,61.5),('inc_c5',56.7,69.7),('inc_c6',58.8,77.4),('inc_c7',62.5,81.9),('xiph',60.9,88.4)]),

 ('ll-155','Стопа, бічна поверхня','Нижня кінцівка',[('tarsus',41.3,6.5),('sinus_tarsi',49.3,6.5),('navic',59.3,5.2),('cun_int',65.8,13.1),('cun_lat',68.0,20.9),('talus',14.3,24.8),('metatarsus',71.8,36.0),('calcaneus',5.3,43.1),('phalanges_p',91.8,54.2),('cuboid',42.3,83.0),('troch_peron',31.3,90.2)]),
 ('ll-156','Надп’яткова кістка, знизу','Нижня кінцівка',[('caput_tali_nav',59.5,5.6),('fac_calc_ant',25.1,17.9),('fac_calc_med',82.9,39.5),('sulcus_tali',37.9,38.6),('proc_lat_tali',29.5,63.1),('fac_calc_post',23.3,74.4),('s_fhl',84.1,85.2),('proc_post_tali',70.3,92.7)]),
 ('ll-157','Надп’яткова кістка, зверху','Нижня кінцівка',[('proc_post_tali_med',49.8,6.7),('troch_tali',25.9,12.0),('s_fhl',75.6,14.9),('corpus_tali',30.3,20.7),('proc_lat_tali',8.1,42.7),('collum_tali',26.7,63.9),('caput_tali',72.4,87.9),('fac_nav',53.4,93.7)]),

 ('ll-151','Великогомілкова кістка, проксимальний кінець (зверху)','Нижня кінцівка',[('area_ic_ant',18.1,4.1),('tub_tib',75.1,8.9),('cond_med_t',8.1,40.9),('cond_lat_t',85.1,39.7),('caput_fib',87.3,46.8),('fac_cap_fib',89.9,58.1),('apex_fib',90.2,74.6),('tub_ic_med',14.1,82.3),('area_ic_post',30.3,91.8),('tub_ic_lat',70.6,96.0)]),
 ('ll-152','Великогомілкова і малогомілкова кістки, дистальні кінці (знизу)','Нижня кінцівка',[('mall_med',38.5,7.0),('fac_mall_lat',82.8,30.5),('mall_lat',85.2,49.2),('fac_mall_med',11.1,58.6),('fac_inf_tib',61.1,89.8)]),
 ('ll-153','Стопа, підошвова поверхня','Нижня кінцівка',[('phal_hal',91.8,13.5),('phalanges_p',11.5,20.5),('sesam',90.1,36.5),('metatarsus',9.3,41.5),('bases_mt',5.8,46.3),('tub_mt1',85.2,46.8),('tub_mt5',7.1,55.0),('cun_med',87.0,56.3),('s_peron',8.9,60.0),('cun_int',86.5,62.0),('tub_cub',8.9,64.0),('tub_nav',85.6,68.8),('cun_lat',7.1,70.5),('tarsus',7.1,73.8),('caput_tali',75.0,86.5),('sustent',60.3,90.8),('proc_lat_calc',19.1,97.0),('proc_med_calc',58.1,97.3)]),
 ('ll-154','Стопа, тильна поверхня','Нижня кінцівка',[('ph3_d2',77.3,3.5),('ph2_d2',81.8,6.3),('ph1_d2',84.9,8.8),('phal_hal',17.5,12.8),('capita_mt',88.9,46.5),('cun_med',12.6,56.5),('cun_int',12.1,62.0),('tub_mt5',88.9,63.8),('cun_lat',85.8,66.3),('tub_nav',11.7,68.8),('cuboid',83.6,69.0),('caput_tali',84.0,76.3),('troch_tali',82.2,79.3),('proc_lat_tali',81.8,82.0),('calcaneus',75.9,90.0)]),

 ('ll-137','Стегнова кістка, задня поверхня','Нижня кінцівка',[('caput_f',9.6,2.3),('troch_maj',76.8,1.8),('collum_f',24.4,16.3),('troch_min',22.2,18.8),('lin_pect',26.6,22.0),('lab_med_la',25.1,31.3),('lab_lat_la',79.8,44.3),('f_popl',80.5,78.3),('epi_med',9.6,80.5),('epi_lat',82.0,80.8),('cond_lat',76.8,93.0),('cond_med',17.0,94.8),('f_intercond',72.4,95.8),('lin_intercond',28.1,98.3)]),
 ('ll-138','Стегнова кістка, присередня поверхня','Нижня кінцівка',[('fovea_f',56.6,2.3),('troch_maj',74.3,4.8),('f_troch',82.8,8.3),('collum_f',13.5,14.5),('troch_min',81.1,21.5),('lin_asp',75.2,35.5),('f_popl',68.4,74.0),('epi_med',71.8,78.8),('cond_lat',72.6,91.5),('cond_med',43.9,94.5)]),
 ('ll-139','Стегнова кістка, передня поверхня','Нижня кінцівка',[('collum_f',53.8,1.5),('troch_maj',35.1,3.8),('fovea_f',87.2,7.3),('lin_intertroch',73.6,17.3),('troch_min',68.5,21.8),('epi_med',75.9,84.3),('epi_lat',8.5,86.5),('f_patel',43.0,98.8)]),
 ('ll-140','Стегнова кістка, проксимальний кінець ззаду','Нижня кінцівка',[('collum_f',52.4,4.2),('troch_maj',85.5,8.0),('caput_f',6.0,25.5),('cr_intertroch',29.8,52.4),('tub_glut',91.5,63.1),('troch_min',36.7,63.8),('lin_pect',40.3,82.8),('lab_lat_la',91.1,86.6),('lab_med_la',40.3,88.5)]),
 ('ll-141','Стегнова кістка, дистальний кінець спереду','Нижня кінцівка',[('f_patel',51.2,4.3),('epi_med',79.3,42.7),('epi_lat',9.5,54.3),('cond_lat',9.1,76.8),('cond_med',88.1,76.2),('f_intercond',57.4,95.1)]),

 ('ll-132','Кульшова кістка, зовнішня (бічна) поверхня','Нижня кінцівка',[('lab_int',72.5,2.5),('lin_interm',73.5,5.5),('lab_ext',73.0,8.8),('crista_il',90.2,5.5),('ala_il',18.8,8.3),('lg_post',8.6,25.2),('sips',8.3,39.8),('sias',86.6,39.5),('corp_il',82.4,42.0),('sipi',8.6,47.0),('siai',85.3,48.6),('lg_ant',17.2,50.9),('inc_isch_maj',18.5,53.3),('lg_inf',18.5,56.4),('f_lunata',74.6,63.0),('f_acet',75.4,68.8),('cr_obt',74.6,73.2),('pecten',74.1,77.1),('spina_isch',13.3,76.0),('inc_isch_min',12.0,79.0),('tub_pub',75.9,79.6),('tuber_isch',12.0,91.5)]),
 ('ll-133','Кульшова кістка, внутрішня поверхня','Нижня кінцівка',[('s_paragl',78.7,10.8),('crista_il',12.3,18.3),('sips',85.7,24.6),('sias',14.0,29.3),('tub_il',88.0,31.6),('sipi',88.0,38.5),('f_auric',88.5,46.0),('siai',13.4,46.0),('inc_isch_maj',79.0,49.3),('lin_arc',26.9,59.8),('spina_isch',88.2,60.4),('tub_obt_post',88.2,65.3),('s_obt',24.6,67.0),('inc_isch_min',90.8,70.0),('pecten',21.6,71.4),('tub_obt_ant',24.6,77.2),('tuber_isch',90.2,77.2),('f_symph',34.5,96.3)]),
 ('ll-134','Кульшова кістка, вигляд спереду','Нижня кінцівка',[('lin_interm',34.8,3.2),('lab_int',28.9,5.6),('lab_ext',10.2,10.2),('sias',55.1,14.2),('ala_il',10.8,27.8),('siai',61.7,35.3),('em_iliopub',65.6,49.5),('corp_pub',64.3,54.6),('acetab',9.5,62.6),('r_sup_pub',72.8,60.5),('pecten',70.9,63.4),('tub_pub',74.5,65.5),('corp_isch',12.1,74.1),('tub_obt_post',9.5,78.1),('r_sup_isch',11.2,81.1),('tuber_isch',14.1,85.1),('r_inf_pub',78.1,91.0),('r_inf_isch',61.7,95.8)]),
 ('ll-135','Кульшова кістка: клубова, сіднича, лобкова (внутрішня поверхня)','Нижня кінцівка',[('crista_il',87.8,5.9),('sias',15.1,38.5),('f_auric',82.7,46.8),('corp_il',30.1,52.1),('corp_isch',86.0,51.8),('em_iliopub',31.0,58.5),('spina_isch',86.9,59.5),('corp_pub',34.6,66.9),('r_sup_isch',89.8,67.8),('ala_il',93.1,72.1),('r_sup_pub',28.4,73.6),('f_symph',31.6,89.0),('r_inf_isch',88.7,89.3),('r_inf_pub',50.5,96.1)]),
 ('ll-136','Кульшова кістка: клубова, сіднича, лобкова (зовнішня поверхня)','Нижня кінцівка',[('crista_il',82.6,3.6),('r_sup_isch',18.5,37.7),('ala_il',22.1,41.6),('corp_il',81.9,46.1),('em_iliopub',84.1,52.4),('corp_pub',84.8,58.8),('corp_isch',13.4,65.4),('r_sup_pub',88.8,66.6),('tuber_isch',16.7,88.6),('r_inf_pub',75.0,91.6),('r_inf_isch',41.7,94.9)]),

 ('ul-121','Променева кістка, передня поверхня','Верхня кінцівка',[('caput_r',44.3,3.8),('collum_r',46.9,8.5),('tub_r',40.8,16.5),('for_nutr',32.1,34.0),('m_inteross',33.9,37.8),('m_ant',44.3,48.0),('f_ant',44.3,59.0),('styl_r',54.7,98.8)]),
 ('ul-122','Променева кістка, присередній край','Верхня кінцівка',[('circ_r',73.9,2.3),('ext_prox',11.8,9.5),('tub_r',77.1,15.0),('f_ant',75.2,31.0),('m_inteross',78.4,38.5),('f_post_r',72.5,56.5),('inc_uln',73.9,89.3),('ext_dist',11.8,94.0),('f_carp',71.9,97.5)]),
 ('ul-123','Променева кістка, задня поверхня','Верхня кінцівка',[('caput_r',33.0,2.3),('corpus_r',35.0,19.5),('m_inteross',85.2,34.5),('m_post',79.7,41.3),('f_lat',19.9,45.0),('f_post_r',80.4,49.8),('styl_r',24.7,95.0)]),
 ('ul-124','Ліктьова і променева кістки, проксимальні кінці','Верхня кінцівка',[('olecr',67.8,12.7),('fovea_r',86.2,22.8),('inc_troch',11.4,40.3),('circ_r',85.8,46.6),('tub_r',82.5,69.9),('Ulna',33.5,94.3),('Radius',57.2,94.3)]),
 ('ul-125','Ліктьова і променева кістки, дистальні кінці','Верхня кінцівка',[('styl_u',7.1,72.5),('styl_r',89.7,32.6),('f_carp',88.3,58.9),('Ulna',23.4,89.7),('Radius',52.1,89.7)]),

 ('ul-108','Лопатка, задня (дорсальна) поверхня','Верхня кінцівка',[('ang_sup',76,7.5),('inc_scap',34,12),('m_sup',49,16),('coracoid',22,17),('spina',89,30),('acromion',9,47),('glenoid',12,53),('m_med',91,57),('ang_lat',16,59),('collum_sc',29,64),('m_lat',34,73),('ang_inf',51,96)]),
 ('ul-109','Лопатка, реброва (передня) поверхня','Верхня кінцівка',[('fac_acr',83,3),('acromion',61,4),('f_subsc',30,6),('coracoid',57,10),('ang_sup',19,10),('m_sup',33,12),('inc_scap',44,14),('glenoid',75,34),('collum_sc',70,43),('m_med',10,56),('m_lat',65,63),('lin_musc',12,65),('ang_inf',39,96)]),
 ('ul-113','Плечова кістка, задня поверхня','Верхня кінцівка',[('caput_h',74,4),('tub_maj',20,8),('ext_prox',20,11),('col_chir',77,15.5),('corpus_h',33,40),('s_rad',80,46),('f_post',74,71),('ext_dist',15,85),('f_olecr',74,85),('epi_med',77,88),('epi_lat',15,90),('trochlea_h',27,95),('s_uln',69,97)]),
 ('ul-114','Плечова кістка, передня поверхня','Верхня кінцівка',[('col_anat',69,4),('caput_h',44,4),('s_intertub',84,7),('tub_maj',87,10),('tub_min',32,18),('cr_maj',84,27),('cr_min',27,28),('tub_delt',78,46),('for_nutr',34,48),('s_rad',9,48),('mh_lat',82,74),('mh_med',28,75),('f_antlat',81,79),('f_antmed',20,80),('f_coron',25,83),('f_rad',81,86),('epi_lat',83,90),('epi_med',24,88.8),('capitulum',83,96),('trochlea_h',32,98)]),
 ('ul-115','Плечова кістка, проксимальний кінець (зверху)','Верхня кінцівка',[('tub_min',79,8),('s_intertub',16,14),('col_anat',12,25),('tub_maj',10,54),('caput_h',92,52.6)]),
 ('ul-116','Плечова кістка, дистальний кінець (спереду)','Верхня кінцівка',[('epi_lat',11,37),('epi_med',91,63),('s_uln',76,70),('capitulum',26,84),('trochlea_h',70,84)]),
]
CREDIT=lambda plate:{'artist':'Sobotta, Atlas and Text-book of Human Anatomy (American ed., 1909)','license':'Public domain','licurl':'','source':'https://commons.wikimedia.org/wiki/File:Sobo_1909_'+plate+'.png'}
def build(dims):
    out=[]
    for slug,title,cat,items in SETS:
        if slug not in dims: print('no dims',slug); continue
        its=[{'n':i+1,'la':T[k][0],'uk':T[k][1],'pts':[[x,y]]} for i,(k,x,y) in enumerate(items)]
        w,h=dims[slug]; plate=slug.split('-')[1]
        out.append({'id':slug,'title':title,'cat':cat,'file':'atlas/'+slug+'.jpg','w':w,'h':h,'items':its,'credit':CREDIT(plate)})
    return out
