# slug: (title, category, file, [(n, la, uk), ...])
SETS = {
 'skeleton': ('Скелет людини (вигляд спереду)', 'Скелет', 'Human skeleton front numbered.svg', [
  (1,'Columna vertebralis','Хребтовий стовп'),(2,'Vertebrae cervicales','Шийні хребці'),(3,'Vertebrae thoracicae','Грудні хребці'),(4,'Vertebrae lumbales','Поперекові хребці'),(5,'Os sacrum','Крижова кістка'),(6,'Os coccygis','Куприк'),(7,'Cranium','Череп'),(8,'Neurocranium','Мозковий череп'),(9,'Mandibula','Нижня щелепа'),(10,'Clavicula','Ключиця'),(11,'Manubrium sterni','Рукоятка груднини'),(12,'Corpus sterni','Тіло груднини'),(13,'Scapula','Лопатка'),(14,'Humerus','Плечова кістка'),(15,'Costae','Ребра'),(16,'Radius','Променева кістка'),(17,'Ulna','Ліктьова кістка'),(18,'Ossa carpi','Кістки зап’ястка'),(19,'Ossa metacarpi','П’ясткові кістки'),(20,'Phalanges digitorum manus','Фаланги пальців кисті'),(21,'Femur','Стегнова кістка'),(22,'Patella','Наколінок'),(23,'Tibia','Великогомілкова кістка'),(24,'Fibula','Малогомілкова кістка'),(25,'Ossa tarsi','Кістки заплесна'),(26,'Ossa metatarsi','Плеснові кістки'),(27,'Phalanges digitorum pedis','Фаланги пальців стопи')]),
 'skull-front': ('Череп спереду: кістки', 'Скелет', 'Human skull front bones numbered.svg', [
  (1,'Os frontale','Лобова кістка'),(2,'Os nasale','Носова кістка'),(3,'Os parietale','Тім’яна кістка'),(4,'Os temporale','Скронева кістка'),(5,'Os sphenoidale','Клиноподібна кістка'),(6,'Os lacrimale','Слізна кістка'),(7,'Os zygomaticum','Вилична кістка'),(8,'Os ethmoidale et vomer','Решітчаста кістка і леміш'),(9,'Maxilla','Верхня щелепа'),(10,'Mandibula','Нижня щелепа')]),
 'skull-side': ('Череп збоку: кістки', 'Скелет', 'Human skull side bones numbered.svg', [
  (1,'Os frontale','Лобова кістка'),(2,'Os parietale','Тім’яна кістка'),(3,'Os nasale','Носова кістка'),(4,'Os lacrimale','Слізна кістка'),(5,'Os ethmoidale','Решітчаста кістка'),(6,'Os sphenoidale','Клиноподібна кістка'),(7,'Os occipitale','Потилична кістка'),(8,'Os temporale','Скронева кістка'),(9,'Os zygomaticum','Вилична кістка'),(10,'Maxilla','Верхня щелепа'),(11,'Mandibula','Нижня щелепа')]),
 'heart': ('Серце: камери, клапани, судини', 'Серце і судини', 'Diagram of the human heart (multilingual).svg', [
  (1,'Vena cava superior','Верхня порожниста вена'),(2,'Arteria pulmonalis','Легенева артерія'),(3,'Venae pulmonales','Легеневі вени'),(4,'Valva mitralis','Мітральний (двостулковий) клапан'),(5,'Valva aortae','Клапан аорти'),(6,'Ventriculus sinister','Лівий шлуночок'),(7,'Ventriculus dexter','Правий шлуночок'),(8,'Atrium sinistrum','Ліве передсердя'),(9,'Atrium dextrum','Праве передсердя'),(10,'Aorta','Аорта'),(11,'Valva trunci pulmonalis','Клапан легеневого стовбура'),(12,'Valva tricuspidalis','Тристулковий клапан'),(13,'Vena cava inferior','Нижня порожниста вена')]),
 'heart-conduction': ('Провідна система серця', 'Серце і судини', 'ConductionsystemoftheheartwithoutHeart.svg', [
  (1,'Nodus sinuatrialis','Синусно-передсердний вузол'),(2,'Fasciculus interatrialis (Bachmann)','Міжпередсердний пучок Бахмана'),(3,'Tractus internodalis anterior','Передній міжвузловий тракт'),(4,'Tractus internodalis medius','Середній міжвузловий тракт'),(5,'Tractus internodalis posterior','Задній міжвузловий тракт'),(6,'Nodus atrioventricularis','Передсердно-шлуночковий вузол'),(7,'Fasciculus atrioventricularis (His)','Передсердно-шлуночковий пучок (Гіса)'),(8,'Crus dextrum','Права ніжка пучка Гіса'),(9,'Crus sinistrum','Ліва ніжка пучка Гіса'),(10,'Fasciculus anterior cruris sinistri','Передня гілка лівої ніжки'),(11,'Fasciculus posterior cruris sinistri','Задня гілка лівої ніжки'),(12,'Rami subendocardiales (fibrae Purkinje)','Волокна Пуркіньє')]),
 'brain': ('Головний мозок: сагітальний розріз', 'Нервова система', 'Encephalon human sagittal section multilingual.svg', [
  (1,'Cerebrum','Великий мозок'),(2,'Telencephalon','Кінцевий мозок'),(3,'Diencephalon','Проміжний мозок'),(4,'Truncus encephali','Стовбур мозку'),(5,'Mesencephalon','Середній мозок'),(6,'Pons','Міст'),(7,'Medulla oblongata','Довгастий мозок'),(8,'Cerebellum','Мозочок'),(9,'Medulla spinalis','Спинний мозок')]),
 'meninges': ('Оболони головного мозку', 'Нервова система', 'Meninges-multilingual.svg', [
  (1,'Cutis','Шкіра'),(2,'Galea aponeurotica','Сухожилковий шолом'),(3,'Pericranium','Окістя черепа'),(4,'Calvaria','Кістка склепіння черепа'),(5,'Meninges','Мозкові оболони'),(6,'Dura mater','Тверда оболона'),(7,'Arachnoidea mater','Павутинна оболона'),(8,'Pia mater','М’яка оболона')]),
 'nervous-system': ('Нервова система: огляд', 'Нервова система', 'Nervous system diagram numbered.svg', [
  (1,'Systema nervosum centrale','Центральна нервова система'),(2,'Cerebrum','Великий мозок'),(3,'Cerebellum','Мозочок'),(4,'Truncus encephali','Стовбур мозку'),(5,'Medulla spinalis','Спинний мозок'),(6,'Nervi craniales','Черепні нерви'),(7,'Nervus vagus','Блукаючий нерв'),(8,'Plexus brachialis','Плечове сплетення'),(9,'Nervus musculocutaneus','М’язово-шкірний нерв'),(10,'Nervus radialis','Променевий нерв'),(11,'Nervus medianus','Серединний нерв'),(12,'Nervus ulnaris','Ліктьовий нерв'),(13,'Nervus cutaneus brachii et antebrachii medialis','Присередній шкірний нерв плеча та передпліччя'),(14,'Nervi intercostales','Міжреброві нерви'),(15,'Nervus subcostalis','Підребровий нерв'),(16,'Nervus iliohypogastricus','Клубово-підчеревний нерв'),(17,'Nervus ilioinguinalis','Клубово-пахвинний нерв'),(18,'Nervus cutaneus femoris lateralis','Бічний шкірний нерв стегна'),(19,'Nervus genitofemoralis','Статево-стегновий нерв'),(20,'Plexus lumbalis','Поперекове сплетення'),(21,'Nervus obturatorius','Затульний нерв'),(22,'Nervus femoralis','Стегновий нерв'),(23,'Rami musculares nervi femoralis','М’язові гілки стегнового нерва'),(24,'Nervus saphenus','Підшкірний нерв'),(25,'Plexus sacralis','Крижове сплетення'),(26,'Nervus ischiadicus','Сідничий нерв'),(27,'Nervus tibialis','Великогомілковий нерв'),(28,'Nervus fibularis communis','Загальний малогомілковий нерв'),(29,'Nervus fibularis profundus','Глибокий малогомілковий нерв'),(30,'Nervus fibularis superficialis','Поверхневий малогомілковий нерв'),(31,'Nervus suralis','Литковий нерв'),(32,'Nervus pudendus','Соромітний нерв')]),
 'eye': ('Очне яблуко', 'Органи чуття', 'Eye scheme mulitlingual.svg', [
  (1,'Sclera','Білкова оболонка (склера)'),(2,'Choroidea','Судинна оболонка'),(3,'Sinus venosus sclerae','Венозна пазуха склери (шлеммів канал)'),(4,'Radix iridis','Корінь райдужки'),(5,'Cornea','Рогівка'),(6,'Iris','Райдужка'),(7,'Pupilla','Зіниця'),(8,'Camera anterior bulbi','Передня камера ока'),(9,'Camera posterior bulbi','Задня камера ока'),(10,'Corpus ciliare','Війкове тіло'),(11,'Lens','Кришталик'),(12,'Corpus vitreum','Скловидне тіло'),(13,'Retina','Сітківка'),(14,'Nervus opticus','Зоровий нерв'),(15,'Fibrae zonulares','Волокна війкового пояска')]),
 'ear': ('Вухо: зовнішнє, середнє, внутрішнє', 'Органи чуття', 'Anatomy of the Human Ear-Number.svg', [
  (1,'Auricula','Вушна раковина'),(2,'Meatus acusticus externus','Зовнішній слуховий хід'),(3,'Membrana tympanica','Барабанна перетинка'),(4,'Cavitas tympani','Барабанна порожнина'),(5,'Fenestra cochleae','Вікно завитки (кругле)'),(6,'Tuba auditiva','Слухова труба'),(7,'Cochlea','Завитка'),(8,'Nervus vestibulocochlearis','Присінково-завитковий нерв'),(9,'Canales semicirculares','Півколові канали'),(10,'Fenestra vestibuli','Вікно присінка (овальне)'),(11,'Stapes','Стремінце'),(12,'Incus','Коваделко'),(13,'Malleus','Молоточок'),(14,'Os temporale','Скронева кістка'),(15,'Auris externa','Зовнішнє вухо'),(16,'Auris media','Середнє вухо'),(17,'Auris interna','Внутрішнє вухо')]),
 'labyrinth': ('Лабіринт внутрішнього вуха', 'Органи чуття', 'Laberinth ear multilingual.svg', [
  (1,'Perilympha','Перилімфа'),(2,'Endolympha','Ендолімфа'),(3,'Canales semicirculares','Півколові канали'),(4,'Canalis semicircularis posterior','Задній півколовий канал'),(5,'Canalis semicircularis lateralis','Бічний півколовий канал'),(6,'Canalis semicircularis anterior','Передній півколовий канал'),(7,'Ampulla ossea','Ампула'),(8,'Vestibulum','Присінок'),(9,'Organa otolithica','Отолітові органи'),(10,'Utriculus','Маточка'),(11,'Sacculus','Мішечок'),(12,'Maculae utriculi et sacculi','Плями маточки й мішечка'),(13,'Ductus endolymphaticus','Ендолімфатична протока'),(14,'Fenestra vestibuli','Вікно присінка'),(15,'Fenestra cochleae','Вікно завитки'),(16,'Ductus perilymphaticus','Перилімфатична протока'),(17,'Cochlea','Завитка'),(18,'Scala tympani','Барабанні сходи'),(19,'Scala vestibuli','Присінкові сходи'),(20,'Ductus cochlearis','Завиткова протока'),(21,'Organum spirale','Спіральний (кортіїв) орган'),(22,'Auris media','Середнє вухо'),(23,'Stapes','Стремінце'),(24,'Cavitas tympani','Барабанна порожнина')]),
 'respiratory': ('Дихальна система', 'Дихальна система', 'Respiratory system complete numbered.svg', [
  (1,'Sinus paranasales','Приносові пазухи'),(2,'Sinus frontalis','Лобова пазуха'),(3,'Sinus sphenoidalis','Клиноподібна пазуха'),(4,'Tractus respiratorius superior','Верхні дихальні шляхи'),(5,'Nasus','Ніс'),(6,'Cavitas nasi','Носова порожнина'),(7,'Conchae nasales','Носові раковини'),(8,'Vestibulum nasi','Присінок носа'),(9,'Pharynx','Глотка'),(10,'Larynx','Гортань'),(11,'Epiglottis','Надгортанник'),(12,'Cartilago thyroidea','Щитоподібний хрящ'),(13,'Cartilago cricoidea','Перснеподібний хрящ'),(14,'Plicae vocales','Голосові складки'),(15,'Tractus respiratorius inferior','Нижні дихальні шляхи'),(16,'Trachea','Трахея'),(17,'Carina tracheae','Кіль трахеї'),(18,'Bronchi principales','Головні бронхи'),(19,'Cartilagines tracheales et bronchiales','Хрящі трахеї та бронхів'),(20,'Bronchi lobares','Часткові бронхи'),(21,'Bronchus lobaris superior','Верхній частковий бронх'),(22,'Bronchus lobaris inferior','Нижній частковий бронх'),(23,'Bronchus lobaris medius','Середній частковий бронх'),(24,'Bronchus lingularis','Язичковий бронх'),(25,'Pulmo dexter','Права легеня'),(26,'Lobus superior pulmonis dextri','Верхня частка правої легені'),(27,'Fissura horizontalis','Горизонтальна щілина'),(28,'Fissura obliqua pulmonis dextri','Коса щілина правої легені'),(29,'Lobus medius','Середня частка'),(30,'Lobus inferior pulmonis dextri','Нижня частка правої легені'),(31,'Pulmo sinister','Ліва легеня'),(32,'Lobus superior pulmonis sinistri','Верхня частка лівої легені'),(33,'Apex pulmonis','Верхівка легені'),(34,'Fissura obliqua pulmonis sinistri','Коса щілина лівої легені'),(35,'Incisura cardiaca','Серцева вирізка'),(36,'Lingula pulmonis','Язичок легені'),(37,'Lobus inferior pulmonis sinistri','Нижня частка лівої легені'),(38,'Diaphragma','Діафрагма'),(39,'Cavitas oris','Ротова порожнина'),(40,'Oesophagus','Стравохід'),(41,'Textus connectivus','Сполучна тканина'),(42,'Sacculi alveolares','Альвеолярні мішечки'),(43,'Ductus alveolaris','Альвеолярна протока'),(44,'Glandula mucosa','Слизова залоза'),(45,'Tunica mucosa','Слизова оболонка'),(46,'Arteria pulmonalis','Легенева артерія'),(47,'Vena pulmonalis','Легенева вена'),(48,'Rete capillare','Капілярна сітка'),(49,'Atrium alveolare','Альвеолярний присінок'),(50,'Alveoli pulmonis','Альвеоли')]),
 'digestive': ('Травна система', 'Травна система', 'Digestive system diagram numbered.svg', [
  (1,'Cavitas oris','Ротова порожнина'),(2,'Palatum','Піднебіння'),(3,'Uvula','Язичок'),(4,'Lingua','Язик'),(5,'Dentes','Зуби'),(6,'Glandulae salivariae','Слинні залози'),(7,'Glandula sublingualis','Під’язикова залоза'),(8,'Glandula submandibularis','Піднижньощелепна залоза'),(9,'Glandula parotidea','Привушна залоза'),(10,'Pharynx','Глотка'),(11,'Oesophagus','Стравохід'),(12,'Hepar','Печінка'),(13,'Vesica biliaris','Жовчний міхур'),(14,'Ductus choledochus','Спільна жовчна протока'),(15,'Gaster','Шлунок'),(16,'Pancreas','Підшлункова залоза'),(17,'Ductus pancreaticus','Протока підшлункової залози'),(18,'Intestinum tenue','Тонка кишка'),(19,'Duodenum','Дванадцятипала кишка'),(20,'Jejunum','Порожня кишка'),(21,'Ileum','Клубова кишка'),(22,'Appendix vermiformis','Червоподібний відросток'),(23,'Intestinum crassum','Товста кишка'),(24,'Colon transversum','Поперечна ободова кишка'),(25,'Colon ascendens','Висхідна ободова кишка'),(26,'Caecum','Сліпа кишка'),(27,'Colon descendens','Низхідна ободова кишка'),(28,'Colon sigmoideum','Сигмоподібна ободова кишка'),(29,'Rectum','Пряма кишка'),(30,'Anus','Відхідник')]),
 'abdomen': ('Органи черевної порожнини', 'Травна система', 'Abdomal organs.svg', [
  (1,'Oesophagus','Стравохід'),(2,'Diaphragma','Діафрагма'),(3,'Gaster','Шлунок'),(4,'Hepar','Печінка'),(5,'Vesica biliaris','Жовчний міхур'),(6,'Duodenum','Дванадцятипала кишка'),(7,'Pancreas','Підшлункова залоза'),(8,'Splen','Селезінка')]),
 'biliary': ('Жовчні шляхи та підшлункова залоза', 'Травна система', 'Biliary system multilingual.svg', [
  (1,'Ductus biliares','Жовчні протоки'),(2,'Ductus biliferi intrahepatici','Внутрішньопечінкові жовчні протоки'),(3,'Ductus hepatici dexter et sinister','Права і ліва печінкові протоки'),(4,'Ductus hepaticus communis','Спільна печінкова протока'),(5,'Ductus cysticus','Міхурова протока'),(6,'Ductus choledochus','Спільна жовчна протока'),(7,'Musculus sphincter ampullae (Oddi)','М’яз-замикач ампули (сфінктер Одді)'),(8,'Papilla duodeni major','Великий сосочок дванадцятипалої кишки'),(9,'Vesica biliaris','Жовчний міхур'),(10,'Lobus hepatis dexter','Права частка печінки'),(11,'Lobus hepatis sinister','Ліва частка печінки'),(12,'Splen','Селезінка'),(13,'Oesophagus','Стравохід'),(14,'Gaster','Шлунок'),(15,'Pancreas','Підшлункова залоза'),(16,'Ductus pancreaticus accessorius','Додаткова протока підшлункової залози'),(17,'Ductus pancreaticus','Протока підшлункової залози'),(18,'Intestinum tenue','Тонка кишка'),(19,'Duodenum','Дванадцятипала кишка'),(20,'Jejunum','Порожня кишка'),(21,'Ren dexter','Права нирка'),(22,'Ren sinister','Ліва нирка')]),
 'colon': ('Товста кишка', 'Травна система', 'Dickdarm-Schema.svg', [
  (1,'Colon ascendens','Висхідна ободова кишка'),(2,'Colon transversum','Поперечна ободова кишка'),(3,'Colon descendens','Низхідна ободова кишка'),(4,'Colon sigmoideum','Сигмоподібна ободова кишка'),(5,'Rectum et canalis analis','Пряма кишка і відхідниковий канал')]),
 'peritoneum': ('Очеревина: сагітальний розріз', 'Травна система', 'Peritoneum.svg', [
  (1,'Diaphragma','Діафрагма'),(2,'Hepar','Печінка'),(3,'Gaster','Шлунок'),(4,'Vesica urinaria','Сечовий міхур'),(5,'Symphysis pubica','Лобковий симфіз'),(6,'Vagina','Піхва'),(7,'Pancreas','Підшлункова залоза'),(8,'Duodenum','Дванадцятипала кишка'),(9,'Colon transversum','Поперечна ободова кишка'),(10,'Intestinum tenue','Тонка кишка'),(11,'Uterus','Матка'),(12,'Rectum','Пряма кишка')]),
 'kidney': ('Нирка: фронтальний розріз', 'Сечова система', 'Kidney multilingual.svg', [
  (1,'Capsula fibrosa renis','Волокниста капсула нирки'),(2,'Cortex renalis','Кіркова речовина'),(3,'Columnae renales','Ниркові стовпи'),(4,'Medulla renalis','Мозкова речовина'),(5,'Pyramis renalis','Ниркова піраміда'),(6,'Papilla renalis','Нирковий сосочок'),(7,'Pelvis renalis','Ниркова миска'),(8,'Calix renalis major','Велика ниркова чашечка'),(9,'Calix renalis minor','Мала ниркова чашечка'),(10,'Ureter','Сечовід'),(11,'Corpusculum renale','Ниркове тільце'),(12,'Arteriola et venula interlobularis','Міжчасточкові артеріола та венула'),(13,'Arteria et vena arcuata','Дугові артерія та вена'),(14,'Arteria et vena interlobaris','Міжчасткові артерія та вена'),(15,'Arteria renalis','Ниркова артерія'),(16,'Vena renalis','Ниркова вена'),(17,'Hilum renale','Ворота нирки'),(18,'Extremitas inferior renis','Нижній кінець (полюс) нирки'),(19,'Corpus adiposum sinus renalis','Жирове тіло ниркової пазухи')]),
 'tooth': ('Зуб: розріз', 'Травна система', 'Tooth Section numbered.svg', [
  (1,'Enamelum','Емаль'),(2,'Dentinum','Дентин'),(3,'Pulpa dentis','Пульпа'),(4,'Gingiva','Ясна'),(5,'Cementum','Цемент'),(6,'Os alveolare','Альвеолярна кістка'),(7,'Vasa sanguinea','Кровоносні судини'),(8,'Nervus','Нерв'),(9,'Corona dentis','Коронка зуба'),(10,'Radix dentis','Корінь зуба')]),
 'thigh-arteries': ('Артерії стегна', 'Серце і судини', 'Thigh arteries schema numbered.svg', [
  (1,'Arteria circumflexa ilium profunda','Глибока огинальна артерія клубової кістки'),(2,'Arteria circumflexa ilium superficialis','Поверхнева огинальна артерія клубової кістки'),(3,'Ramus ascendens arteriae circumflexae femoris lateralis','Висхідна гілка бічної огинальної артерії стегна'),(4,'Ramus transversus arteriae circumflexae femoris lateralis','Поперечна гілка бічної огинальної артерії стегна'),(5,'Arteria circumflexa femoris lateralis','Бічна огинальна артерія стегна'),(6,'Ramus descendens arteriae circumflexae femoris lateralis','Низхідна гілка бічної огинальної артерії стегна'),(7,'Arteria profunda femoris','Глибока артерія стегна'),(8,'Arteriae perforantes','Пронизні артерії'),(9,'Arteria superior lateralis genus','Бічна верхня колінна артерія'),(10,'Rete articulare genus','Колінна суглобова сітка'),(11,'Arteria inferior lateralis genus','Бічна нижня колінна артерія'),(12,'Ramus circumflexus fibularis arteriae tibialis anterioris','Малогомілкова огинальна гілка передньої великогомілкової артерії'),(13,'Arteria tibialis anterior','Передня великогомілкова артерія'),(14,'Arteria iliaca externa','Зовнішня клубова артерія'),(15,'Arteria epigastrica inferior','Нижня надчеревна артерія'),(16,'Arteria epigastrica superficialis','Поверхнева надчеревна артерія'),(17,'Arteria pudenda externa superficialis','Поверхнева зовнішня соромітна артерія'),(18,'Arteria pudenda externa profunda','Глибока зовнішня соромітна артерія'),(19,'Arteria obturatoria','Затульна артерія'),(20,'Arteria femoralis','Стегнова артерія'),(21,'Arteria circumflexa femoris medialis','Присередня огинальна артерія стегна'),(22,'Rami musculares','М’язові гілки'),(23,'Hiatus adductorius','Привідний розтвір'),(24,'Arteria descendens genus','Низхідна колінна артерія'),(25,'Ramus articularis arteriae descendentis genus','Суглобова гілка низхідної колінної артерії'),(26,'Ramus saphenus arteriae descendentis genus','Підшкірна гілка низхідної колінної артерії'),(27,'Arteria superior medialis genus','Присередня верхня колінна артерія'),(28,'Arteria inferior medialis genus','Присередня нижня колінна артерія')]),
 'capillary': ('Мікроциркуляторне русло', 'Серце і судини', 'Illu capillary numbers.svg', [
  (1,'Vasa capillaria','Кровоносні капіляри'),(2,'Pars arteriosa capillaris','Артеріальний відділ капіляра'),(3,'Pars venosa capillaris','Венозний відділ капіляра'),(4,'Vas lymphocapillare','Лімфатичний капіляр'),(5,'Arteriola','Артеріола'),(6,'Venula','Венула'),(7,'Vas lymphaticum','Лімфатична судина'),(8,'Cellulae','Клітини тканини'),(9,'Spatia intercellularia','Міжклітинні простори'),(10,'Liquor interstitialis','Тканинна рідина')]),
}
