"""3D-набори м'язів із Z-Anatomy: група м'язів (+ кістки для контексту) → models/<id>.glb + набір у data.js.
Кожен м'яз — окремий меш; пін = вершина меша, найближча до його центроїда (на поверхні)."""
import trimesh, numpy as np, json, re, os, shutil, sys
A = '/Users/zxc/PycharmProjects/anat/'
MUSC = trimesh.load('MuscularSystem100.glb', force='scene'); SKEL = trimesh.load('SkeletalSystem100.glb', force='scene')
def paths(sc):
    parent = {}
    for e in sc.graph.to_edgelist(): parent[e[1]] = e[0]
    def path(n):
        p = [n]
        while n in parent: n = parent[n]; p.append(n)
        return list(reversed(p))
    return path
PM, PS = paths(MUSC), paths(SKEL)
RED = [196, 74, 70, 255]; BONE = [236, 229, 212, 255]; TEND = [242, 236, 222, 255]
TENDISH = re.compile(r'tendon|ligament|aponeurosis|retinaculum|tract|linea alba|tendinous|tarsus|trochlea|sheath', re.I)

# англ. → (латина, українська); «частини» позначаємо через caput/pars
LA = {
 'Bucinator':('Musculus buccinator','Щічний м’яз'),'Corrugator supercilii':('Musculus corrugator supercilii','М’яз-зморщувач брови'),'Deep part of masseter':('Pars profunda musculi masseteris','Глибока частина жувального м’яза'),'Superficial part of masseter':('Pars superficialis musculi masseteris','Поверхнева частина жувального м’яза'),
 'Depressor anguli oris':('Musculus depressor anguli oris','М’яз-опускач кута рота'),'Depressor labii inferioris':('Musculus depressor labii inferioris','М’яз-опускач нижньої губи'),'Depressor septi nasi':('Musculus depressor septi nasi','М’яз-опускач перегородки носа'),'Epicranial aponeurosis':('Galea aponeurotica','Сухожилковий шолом'),
 'Frontalis muscle':('Venter frontalis musculi occipitofrontalis','Лобове черевце потилично-лобового м’яза'),'Occipitalis muscle':('Venter occipitalis musculi occipitofrontalis','Потиличне черевце потилично-лобового м’яза'),'Genioglossus muscle':('Musculus genioglossus','Підборідно-язиковий м’яз'),'Hyoglossus muscle':('Musculus hyoglossus','Під’язиково-язиковий м’яз'),
 'Inferior head of lateral pterygoid muscle':('Caput inferius musculi pterygoidei lateralis','Нижня головка бічного крилоподібного м’яза'),'Superior head of lateral pterygoid muscle':('Caput superius musculi pterygoidei lateralis','Верхня головка бічного крилоподібного м’яза'),'Medial pterygoid muscle':('Musculus pterygoideus medialis','Присередній крилоподібний м’яз'),
 'Inferior oblique muscle':('Musculus obliquus inferior bulbi','Нижній косий м’яз ока'),'Superior oblique muscle':('Musculus obliquus superior bulbi','Верхній косий м’яз ока'),'Inferior rectus muscle':('Musculus rectus inferior bulbi','Нижній прямий м’яз ока'),'Superior rectus muscle':('Musculus rectus superior bulbi','Верхній прямий м’яз ока'),'Lateral rectus muscle':('Musculus rectus lateralis bulbi','Бічний прямий м’яз ока'),'Medial rectus muscle':('Musculus rectus medialis bulbi','Присередній прямий м’яз ока'),'Levator palpebrae superioris':('Musculus levator palpebrae superioris','М’яз-підіймач верхньої повіки'),
 'Levator anguli oris':('Musculus levator anguli oris','М’яз-підіймач кута рота'),'Levator labii superioris':('Musculus levator labii superioris','М’яз-підіймач верхньої губи'),'Levator nasolabialis':('Musculus levator labii superioris alaeque nasi','М’яз-підіймач верхньої губи і крила носа'),'Mentalis muscle':('Musculus mentalis','Підборідний м’яз'),'Nasalis muscle':('Musculus nasalis','Носовий м’яз'),
 'Orbicularis oris muscle':('Musculus orbicularis oris','Коловий м’яз рота'),'Orbital part of orbicularis oculi':('Pars orbitalis musculi orbicularis oculi','Очноямкова частина колового м’яза ока'),'Palpebral part of orbicularis oculi':('Pars palpebralis musculi orbicularis oculi','Повікова частина колового м’яза ока'),'Palatopharyngeus muscle':('Musculus palatopharyngeus','Піднебінно-глотковий м’яз'),
 'Procerus muscle':('Musculus procerus','М’яз гордіїв'),'Risorius muscle':('Musculus risorius','М’яз сміху'),'Temporalis muscle':('Musculus temporalis','Скроневий м’яз'),'Temporoparietalis muscle':('Musculus temporoparietalis','Скронево-тім’яний м’яз'),'Zygomaticus major muscle':('Musculus zygomaticus major','Великий виличний м’яз'),'Zygomaticus minor muscle':('Musculus zygomaticus minor','Малий виличний м’яз'),
 'Anterior belly of digastric muscle':('Venter anterior musculi digastrici','Переднє черевце двочеревцевого м’яза'),'Posterior belly of digastric muscle':('Venter posterior musculi digastrici','Заднє черевце двочеревцевого м’яза'),'Geniohyoid muscle':('Musculus geniohyoideus','Підборідно-під’язиковий м’яз'),'Mylohyoid muscle':('Musculus mylohyoideus','Щелепно-під’язиковий м’яз'),
 'Inferior pharyngeal constrictor':('Musculus constrictor pharyngis inferior','Нижній м’яз-звужувач глотки'),'Middle pharyngeal constrictor':('Musculus constrictor pharyngis medius','Середній м’яз-звужувач глотки'),'Superior pharyngeal constrictor':('Musculus constrictor pharyngis superior','Верхній м’яз-звужувач глотки'),'Stylopharyngeus muscle':('Musculus stylopharyngeus','Шило-глотковий м’яз'),
 'Longus capitis muscle':('Musculus longus capitis','Довгий м’яз голови'),'Longus colli muscle':('Musculus longus colli','Довгий м’яз шиї'),'Omohyoid muscle':('Musculus omohyoideus','Лопатково-під’язиковий м’яз'),'Platysma':('Platysma','Підшкірний м’яз шиї'),'Rectus anterior capitis muscle':('Musculus rectus capitis anterior','Передній прямий м’яз голови'),'Rectus lateralis capitis muscle':('Musculus rectus capitis lateralis','Бічний прямий м’яз голови'),
 'Scalenus anterior muscle':('Musculus scalenus anterior','Передній драбинчастий м’яз'),'Scalenus medius muscle':('Musculus scalenus medius','Середній драбинчастий м’яз'),'Scalenus posterior muscle':('Musculus scalenus posterior','Задній драбинчастий м’яз'),'Sternocleidomastoid muscle':('Musculus sternocleidomastoideus','Груднинно-ключично-соскоподібний м’яз'),
 'Sternohyoid muscle':('Musculus sternohyoideus','Груднинно-під’язиковий м’яз'),'Sternothyroid muscle':('Musculus sternothyroideus','Груднинно-щитоподібний м’яз'),'Stylohyoid muscle':('Musculus stylohyoideus','Шило-під’язиковий м’яз'),'Thyrohyoid muscle':('Musculus thyrohyoideus','Щито-під’язиковий м’яз'),
 'Straight part of cricothyroid muscle':('Pars recta musculi cricothyroidei','Пряма частина персне-щитоподібного м’яза'),'Oblique part of cricothyroid muscle':('Pars obliqua musculi cricothyroidei','Коса частина персне-щитоподібного м’яза'),'Posterior crico-arytenoid muscle':('Musculus cricoarytenoideus posterior','Задній персне-черпакуватий м’яз'),'Lateral crico-arytenoid muscle':('Musculus cricoarytenoideus lateralis','Бічний персне-черпакуватий м’яз'),'Transverse arytenoid muscle':('Musculus arytenoideus transversus','Поперечний черпакуватий м’яз'),
 'Iliocostalis colli muscle':('Musculus iliocostalis cervicis','Клубово-ребровий м’яз шиї'),'Iliocostalis lumborum muscle':('Musculus iliocostalis lumborum','Клубово-ребровий м’яз попереку'),'Iliocostalis thoracis muscle':('Musculus iliocostalis thoracis','Клубово-ребровий м’яз грудей'),'Interspinales colli muscles':('Musculi interspinales cervicis','Міжостьові м’язи шиї'),'Interspinales lumborum muscles':('Musculi interspinales lumborum','Міжостьові м’язи попереку'),'Interspinales thoracis muscles':('Musculi interspinales thoracis','Міжостьові м’язи грудей'),
 'Longissimus capitis muscle':('Musculus longissimus capitis','Найдовший м’яз голови'),'Longissimus colli muscle':('Musculus longissimus cervicis','Найдовший м’яз шиї'),'Longissimus thoracis muscle':('Musculus longissimus thoracis','Найдовший м’яз грудей'),'Multifidus colli muscle':('Musculus multifidus cervicis','Багатороздільний м’яз шиї'),'Multifidus lumborum muscle':('Musculus multifidus lumborum','Багатороздільний м’яз попереку'),'Multifidus thoracis muscle':('Musculus multifidus thoracis','Багатороздільний м’яз грудей'),
 'Obliquus inferior capitis muscle':('Musculus obliquus capitis inferior','Нижній косий м’яз голови'),'Obliquus superior capitis muscle':('Musculus obliquus capitis superior','Верхній косий м’яз голови'),'Rectus posterior major capitis muscle':('Musculus rectus capitis posterior major','Великий задній прямий м’яз голови'),'Rectus posterior minor capitis muscle':('Musculus rectus capitis posterior minor','Малий задній прямий м’яз голови'),
 'Rotatores':('Musculi rotatores','М’язи-обертачі'),'Semispinalis colli muscle':('Musculus semispinalis cervicis','Півостьовий м’яз шиї'),'Semispinalis thoracis muscle':('Musculus semispinalis thoracis','Півостьовий м’яз грудей'),'Spinalis capitis muscle':('Musculus spinalis capitis','Остьовий м’яз голови'),'Spinalis colli muscle':('Musculus spinalis cervicis','Остьовий м’яз шиї'),'Spinalis thoracis muscle':('Musculus spinalis thoracis','Остьовий м’яз грудей'),'Splenius capitis muscle':('Musculus splenius capitis','Ремінний м’яз голови'),'Splenius colli muscle':('Musculus splenius cervicis','Ремінний м’яз шиї'),
 'Levator scapulae':('Musculus levator scapulae','М’яз-підіймач лопатки'),'Rhomboid major muscle':('Musculus rhomboideus major','Великий ромбоподібний м’яз'),'Rhomboid minor muscle':('Musculus rhomboideus minor','Малий ромбоподібний м’яз'),'Latissimus dorsi muscle':('Musculus latissimus dorsi','Найширший м’яз спини'),
 'Ascending part of trapezius muscle':('Pars ascendens musculi trapezii','Висхідна частина трапецієподібного м’яза'),'Descending part of trapezius muscle':('Pars descendens musculi trapezii','Низхідна частина трапецієподібного м’яза'),'Transverse part of trapezius muscle':('Pars transversa musculi trapezii','Поперечна частина трапецієподібного м’яза'),
 'Serratus posterior superior muscle':('Musculus serratus posterior superior','Верхній задній зубчастий м’яз'),'Serratus posterior inferior muscle':('Musculus serratus posterior inferior','Нижній задній зубчастий м’яз'),'Dorsal parts of lateral intertransversarii lumborum muscles':('Musculi intertransversarii laterales lumborum (partes dorsales)','Бічні міжпоперечні м’язи попереку (дорсальні частини)'),'Ventral parts of lateral intertransversarii lumborum muscles':('Musculi intertransversarii laterales lumborum (partes ventrales)','Бічні міжпоперечні м’язи попереку (вентральні частини)'),
 'Diaphragm_node':('Diaphragma','Діафрагма'),'(Abdominal part of pectoralis major muscle)':('Pars abdominalis musculi pectoralis majoris','Черевна частина великого грудного м’яза'),'Clavicular head of pectoralis major muscle':('Pars clavicularis musculi pectoralis majoris','Ключична частина великого грудного м’яза'),'Sternocostal head of pectoralis major muscle':('Pars sternocostalis musculi pectoralis majoris','Груднинно-реброва частина великого грудного м’яза'),
 'External intercostal muscles':('Musculi intercostales externi','Зовнішні міжреброві м’язи'),'Internal intercostal muscles':('Musculi intercostales interni','Внутрішні міжреброві м’язи'),'Innermost intercostal muscles':('Musculi intercostales intimi','Найглибші міжреброві м’язи'),'Levatores breves costarum':('Musculi levatores costarum breves','Короткі м’язи-підіймачі ребер'),'Levatores longi costarum':('Musculi levatores costarum longi','Довгі м’язи-підіймачі ребер'),
 'Pectoralis minor muscle':('Musculus pectoralis minor','Малий грудний м’яз'),'Serratus anterior muscle':('Musculus serratus anterior','Передній зубчастий м’яз'),'Subclavius muscle':('Musculus subclavius','Підключичний м’яз'),'Transversus thoracis muscle':('Musculus transversus thoracis','Поперечний м’яз грудної клітки'),
 'External abdominal oblique muscle':('Musculus obliquus externus abdominis','Зовнішній косий м’яз живота'),'Internal abdominal oblique muscle':('Musculus obliquus internus abdominis','Внутрішній косий м’яз живота'),'Transversus abdominis muscle':('Musculus transversus abdominis','Поперечний м’яз живота'),'Rectus abdominis muscle':('Musculus rectus abdominis','Прямий м’яз живота'),'Pyramidalis muscle':('Musculus pyramidalis','Пірамідний м’яз'),'Quadratus lumborum muscle':('Musculus quadratus lumborum','Квадратний м’яз попереку'),'Inguinal ligament':('Ligamentum inguinale','Пахвинна зв’язка'),'Linea alba':('Linea alba','Біла лінія живота'),
 'Coccygeus muscle':('Musculus coccygeus','Куприковий м’яз'),'External anal sphincter':('Musculus sphincter ani externus','Зовнішній м’яз-замикач відхідника'),'Iliococcygeus muscle':('Musculus iliococcygeus','Клубово-куприковий м’яз'),'Pubo-analis muscle':('Musculus puboanalis','Лобково-відхідниковий м’яз'),'Pubococcygeus muscle':('Musculus pubococcygeus','Лобково-куприковий м’яз'),'Tendinous arch of levator ani':('Arcus tendineus musculi levatoris ani','Сухожилкова дуга м’яза-підіймача відхідника'),
 'Abductor digiti minimi of hand':('Musculus abductor digiti minimi manus','Відвідний м’яз мізинця кисті'),'Abductor pollicis brevis':('Musculus abductor pollicis brevis','Короткий відвідний м’яз великого пальця'),'Abductor pollicis longus':('Musculus abductor pollicis longus','Довгий відвідний м’яз великого пальця'),'Acromial part of deltoid muscle':('Pars acromialis musculi deltoidei','Надплечова частина дельтоподібного м’яза'),'Clavicular part of deltoid muscle':('Pars clavicularis musculi deltoidei','Ключична частина дельтоподібного м’яза'),'Scapular spinal part of deltoid muscle':('Pars spinalis musculi deltoidei','Остьова частина дельтоподібного м’яза'),
 'Anconeus muscle':('Musculus anconeus','Ліктьовий м’яз'),'Brachialis muscle':('Musculus brachialis','Плечовий м’яз'),'Brachioradialis muscle':('Musculus brachioradialis','Плечо-променевий м’яз'),'Coracobrachialis muscle':('Musculus coracobrachialis','Дзьобо-плечовий м’яз'),'Deep head of flexor pollicis brevis':('Caput profundum musculi flexoris pollicis brevis','Глибока головка короткого м’яза-згинача великого пальця'),'Superficial head of flexor pollicis brevis':('Caput superficiale musculi flexoris pollicis brevis','Поверхнева головка короткого м’яза-згинача великого пальця'),
 'Deep head of pronator teres':('Caput ulnare musculi pronatoris teretis','Ліктьова головка круглого м’яза-привертача'),'Superficial head of pronator teres':('Caput humerale musculi pronatoris teretis','Плечова головка круглого м’яза-привертача'),'Dorsal interossei muscles of hand':('Musculi interossei dorsales manus','Тильні міжкісткові м’язи кисті'),'Palmar interossei muscles':('Musculi interossei palmares','Долонні міжкісткові м’язи'),
 'Extensor carpi radialis brevis':('Musculus extensor carpi radialis brevis','Короткий променевий м’яз-розгинач зап’ястка'),'Extensor carpi radialis longus':('Musculus extensor carpi radialis longus','Довгий променевий м’яз-розгинач зап’ястка'),'Extensor digiti minimi':('Musculus extensor digiti minimi','М’яз-розгинач мізинця'),'Extensor digitorum':('Musculus extensor digitorum','М’яз-розгинач пальців'),'Extensor indicis':('Musculus extensor indicis','М’яз-розгинач вказівного пальця'),'Extensor pollicis brevis':('Musculus extensor pollicis brevis','Короткий м’яз-розгинач великого пальця'),'Extensor pollicis longus':('Musculus extensor pollicis longus','Довгий м’яз-розгинач великого пальця'),
 'Flexor carpi radialis':('Musculus flexor carpi radialis','Променевий м’яз-згинач зап’ястка'),'Flexor digiti minimi of hand':('Musculus flexor digiti minimi brevis manus','Короткий м’яз-згинач мізинця кисті'),'Flexor digitorum profundus':('Musculus flexor digitorum profundus','Глибокий м’яз-згинач пальців'),'Flexor pollicis longus':('Musculus flexor pollicis longus','Довгий м’яз-згинач великого пальця'),
 'Humeral head of extensor carpi ulnaris':('Caput humerale musculi extensoris carpi ulnaris','Плечова головка ліктьового м’яза-розгинача зап’ястка'),'Ulnar head of extensor carpi ulnaris':('Caput ulnare musculi extensoris carpi ulnaris','Ліктьова головка ліктьового м’яза-розгинача зап’ястка'),'Humeral head of flexor carpi ulnaris':('Caput humerale musculi flexoris carpi ulnaris','Плечова головка ліктьового м’яза-згинача зап’ястка'),'Ulnar head of flexor carpi ulnaris':('Caput ulnare musculi flexoris carpi ulnaris','Ліктьова головка ліктьового м’яза-згинача зап’ястка'),
 'Humero-ulnar head of flexor digitorum superficialis':('Caput humeroulnare musculi flexoris digitorum superficialis','Плечо-ліктьова головка поверхневого м’яза-згинача пальців'),'Radial head of flexor digitorum superficialis':('Caput radiale musculi flexoris digitorum superficialis','Променева головка поверхневого м’яза-згинача пальців'),
 'Infraspinatus muscle':('Musculus infraspinatus','Підостьовий м’яз'),'Lateral head of triceps brachii':('Caput laterale musculi tricipitis brachii','Бічна головка триголового м’яза плеча'),'Long head of triceps brachii':('Caput longum musculi tricipitis brachii','Довга головка триголового м’яза плеча'),'Medial head of triceps brachii':('Caput mediale musculi tricipitis brachii','Присередня головка триголового м’яза плеча'),
 'Long head of biceps brachii':('Caput longum musculi bicipitis brachii','Довга головка двоголового м’яза плеча'),'Short head of biceps brachii':('Caput breve musculi bicipitis brachii','Коротка головка двоголового м’яза плеча'),'Lumbrical muscles of hand':('Musculi lumbricales manus','Червоподібні м’язи кисті'),'Oblique head of adductor pollicis':('Caput obliquum musculi adductoris pollicis','Коса головка привідного м’яза великого пальця'),'Transverse head of adductor pollicis':('Caput transversum musculi adductoris pollicis','Поперечна головка привідного м’яза великого пальця'),
 'Opponens digiti minimi muscle of hand':('Musculus opponens digiti minimi manus','Протиставний м’яз мізинця кисті'),'Opponens pollicis muscle':('Musculus opponens pollicis','Протиставний м’яз великого пальця'),'Palmaris longus muscle':('Musculus palmaris longus','Довгий долонний м’яз'),'Pronator quadratus':('Musculus pronator quadratus','Квадратний м’яз-привертач'),'Subscapularis muscle':('Musculus subscapularis','Підлопатковий м’яз'),'Supinator':('Musculus supinator','М’яз-відвертач'),'Supraspinatus muscle':('Musculus supraspinatus','Надостьовий м’яз'),'Teres major muscle':('Musculus teres major','Великий круглий м’яз'),'Teres minor muscle':('Musculus teres minor','Малий круглий м’яз'),
 '(Adductor minimus)':('Musculus adductor minimus','Найменший привідний м’яз'),'(Opponens digiti minimi muscle of foot)':('Musculus opponens digiti minimi pedis','Протиставний м’яз мізинця стопи'),'Abductor digiti minimi of foot':('Musculus abductor digiti minimi pedis','Відвідний м’яз мізинця стопи'),'Abductor hallucis':('Musculus abductor hallucis','Відвідний м’яз великого пальця стопи'),'Adductor brevis':('Musculus adductor brevis','Короткий привідний м’яз'),'Adductor longus':('Musculus adductor longus','Довгий привідний м’яз'),'Adductor magnus':('Musculus adductor magnus','Великий привідний м’яз'),
 'Calcaneal tendon':('Tendo calcaneus (Achillis)','П’ятковий (ахіллів) сухожилок'),'Dorsal interossei muscles of foot':('Musculi interossei dorsales pedis','Тильні міжкісткові м’язи стопи'),'Plantar interossei muscles':('Musculi interossei plantares','Підошовні міжкісткові м’язи'),'Extensor digitorum brevis':('Musculus extensor digitorum brevis','Короткий м’яз-розгинач пальців стопи'),'Extensor digitorum longus':('Musculus extensor digitorum longus','Довгий м’яз-розгинач пальців стопи'),'Extensor hallucis brevis':('Musculus extensor hallucis brevis','Короткий м’яз-розгинач великого пальця стопи'),'Extensor hallucis longus':('Musculus extensor hallucis longus','Довгий м’яз-розгинач великого пальця стопи'),
 'Fibularis brevis muscle':('Musculus fibularis brevis','Короткий малогомілковий м’яз'),'Fibularis longus muscle':('Musculus fibularis longus','Довгий малогомілковий м’яз'),'Fibularis tertius muscle':('Musculus fibularis tertius','Третій малогомілковий м’яз'),'Flexor digiti minimi of foot':('Musculus flexor digiti minimi brevis pedis','Короткий м’яз-згинач мізинця стопи'),'Flexor digitorum brevis':('Musculus flexor digitorum brevis','Короткий м’яз-згинач пальців стопи'),'Flexor digitorum longus':('Musculus flexor digitorum longus','Довгий м’яз-згинач пальців стопи'),'Flexor hallucis longus':('Musculus flexor hallucis longus','Довгий м’яз-згинач великого пальця стопи'),
 'Gluteus maximus muscle':('Musculus gluteus maximus','Великий сідничний м’яз'),'Gluteus medius muscle':('Musculus gluteus medius','Середній сідничний м’яз'),'Gluteus minimus muscle':('Musculus gluteus minimus','Малий сідничний м’яз'),'Gracilis muscle':('Musculus gracilis','Тонкий м’яз'),'Iliacus muscle':('Musculus iliacus','Клубовий м’яз'),'Psoas major':('Musculus psoas major','Великий поперековий м’яз'),'Iliotibial tract':('Tractus iliotibialis','Клубово-великогомілкове пасмо'),
 'Inferior gemellus muscle':('Musculus gemellus inferior','Нижній близнюковий м’яз'),'Superior gemellus muscle':('Musculus gemellus superior','Верхній близнюковий м’яз'),'Lateral head of flexor hallucis brevis':('Caput laterale musculi flexoris hallucis brevis','Бічна головка короткого м’яза-згинача великого пальця'),'Medial head of flexor hallucis brevis':('Caput mediale musculi flexoris hallucis brevis','Присередня головка короткого м’яза-згинача великого пальця'),
 'Lateral head of gastrocnemius':('Caput laterale musculi gastrocnemii','Бічна головка литкового м’яза'),'Medial head of gastrocnemius':('Caput mediale musculi gastrocnemii','Присередня головка литкового м’яза'),'Lateral patellar retinaculum':('Retinaculum patellae laterale','Бічний тримач наколінка'),'Medial patellar retinaculum':('Retinaculum patellae mediale','Присередній тримач наколінка'),
 'Long head of biceps femoris':('Caput longum musculi bicipitis femoris','Довга головка двоголового м’яза стегна'),'Short head of biceps femoris':('Caput breve musculi bicipitis femoris','Коротка головка двоголового м’яза стегна'),'Lumbrical muscles of foot':('Musculi lumbricales pedis','Червоподібні м’язи стопи'),'Oblique head of adductor hallucis':('Caput obliquum musculi adductoris hallucis','Коса головка привідного м’яза великого пальця'),'Transverse head of adductor hallucis':('Caput transversum musculi adductoris hallucis','Поперечна головка привідного м’яза великого пальця'),
 'Obturator externus':('Musculus obturatorius externus','Зовнішній затульний м’яз'),'Obturator internus':('Musculus obturatorius internus','Внутрішній затульний м’яз'),'Pectineus muscle':('Musculus pectineus','Гребінний м’яз'),'Piriformis muscle':('Musculus piriformis','Грушоподібний м’яз'),'Plantaris muscle':('Musculus plantaris','Підошовний м’яз'),'Popliteus muscle':('Musculus popliteus','Підколінний м’яз'),'Quadratus femoris muscle':('Musculus quadratus femoris','Квадратний м’яз стегна'),'Quadratus plantae muscle':('Musculus quadratus plantae','Квадратний м’яз підошви'),
 'Rectus femoris muscle':('Musculus rectus femoris','Прямий м’яз стегна'),'Sartorius muscle':('Musculus sartorius','Кравецький м’яз'),'Semimembranosus muscle':('Musculus semimembranosus','Півперетинчастий м’яз'),'Semitendinosus muscle':('Musculus semitendinosus','Півсухожилковий м’яз'),'Soleus muscle':('Musculus soleus','Камбалоподібний м’яз'),'Tendon of extensor digitorum longus':('Tendo musculi extensoris digitorum longi','Сухожилок довгого м’яза-розгинача пальців'),'Tensor fasciae latae':('Musculus tensor fasciae latae','М’яз-натягувач широкої фасції'),
 'Tibialis anterior muscle':('Musculus tibialis anterior','Передній великогомілковий м’яз'),'Tibialis posterior muscle':('Musculus tibialis posterior','Задній великогомілковий м’яз'),'Vastus intermedius muscle':('Musculus vastus intermedius','Проміжний широкий м’яз'),'Vastus lateralis muscle':('Musculus vastus lateralis','Бічний широкий м’яз'),'Vastus medialis muscle':('Musculus vastus medialis','Присередній широкий м’яз'),
}
SKIP = re.compile(r'Common tendinous ring|tarsus|Trochlea|Intermediate tendon|arytenoid|epiglottic|thyro-arytenoid', re.I)
SETS = [
 dict(id='v3-musc-arm', title='М’язи верхньої кінцівки — 3D', topics=['m1:23','m1:24'], groups=['Muscles of upper limb.g'], sides=('r',), bones=['Scapula.r','Clavicle.r','Humerus.r','Radius.r','Ulna.r'], bone_groups=['Bones of hand.g']),
 dict(id='v3-musc-leg', title='М’язи нижньої кінцівки — 3D', topics=['m1:25','m1:26','m1:27'], groups=['Muscles of lower limb.g'], sides=('r',), bones=['Hip bone.r','Femur.r','Patella.r','Tibia.r','Fibula.r'], bone_groups=['Bones of foot.g']),
 dict(id='v3-musc-back', title='М’язи спини — 3D', topics=['m1:19'], groups=['Epaxial muscles.g','Hypaxial muscles of back.g'], sides=('r','l'), bones=['Hip bone.r','Hip bone.l','Scapula.r','Scapula.l'], bone_groups=['Vertebral column.g']),
 dict(id='v3-musc-thorax-abd', title='М’язи грудей і живота — 3D', topics=['m1:20','m1:21'], groups=['Muscles of thorax.g','Muscles of abdomen.g','Thoracic part of muscular system.g'], sides=('r','l'), frac=(0.28, 0.12), bones=['Hip bone.r','Hip bone.l','Clavicle.r','Clavicle.l'], bone_groups=['Thoracic skeleton.g']),
 dict(id='v3-musc-head-neck', title='М’язи голови та шиї — 3D', topics=['m1:20','m1:22'], groups=['Muscles of head.g','Muscles of neck.g'], sides=('r','l'), frac=(0.4, 0.15), bones=['Mandible','Hyoid bone','Clavicle.r','Clavicle.l'], bone_groups=['Cranium.g']),
]
def side_ok(n, sides):
    m = re.search(r'\.(r|l)$', n)
    return (m.group(1) in sides) if m else True
def collect(sc, path, groups, sides, names=()):
    out = []
    for n in sc.graph.nodes_geometry:
        if n.endswith('.j'): continue
        p = path(n); base = re.sub(r'_[0-9a-f]{6}$', '', n)
        if not (any(g in p for g in groups) or base in names): continue
        if not side_ok(base, sides): continue
        T, gname = sc.graph[n]; m = sc.geometry[gname].copy(); m.apply_transform(T)
        out.append((base, m))
    return out
import fast_simplification
def simplify(m, frac):
    """залишити frac граней (fast_simplification)"""
    if len(m.faces) <= 200: return m
    try:
        v, f = fast_simplification.simplify(np.asarray(m.vertices, dtype=np.float32), np.asarray(m.faces, dtype=np.int32), target_reduction=1 - frac)
        return trimesh.Trimesh(vertices=v, faces=f, process=False)
    except Exception as e:
        print('simplify fail', e); return m
os.makedirs('glb', exist_ok=True); out_sets = []
for S in SETS:
    musc = collect(MUSC, PM, S['groups'], S['sides'])
    bones = collect(SKEL, PS, S.get('bone_groups', []), S['sides'], S['bones'])
    bones = [(n, m) for n, m in bones if not re.search(r'\.(o|e|e1)[rl]$|\.i$', n)]   # без ділянок початку/прикріплення
    allm = trimesh.util.concatenate([m for _, m in musc + bones]); c = allm.bounds.mean(axis=0); s = 1.0 / np.max(allm.extents)
    scene = trimesh.Scene(); items = []; seen = set()
    for i, (n, m) in enumerate(musc + bones):
        is_bone = i >= len(musc); m.apply_translation(-c); m.apply_scale(s)
        fm, fb = S.get('frac', (0.5, 0.18 if len(bones) > 60 else 0.45)); m = simplify(m, fb if is_bone else fm); m.merge_vertices()
        base = re.sub(r'\.(r|l)$', '', n); col = BONE if is_bone else (TEND if TENDISH.search(base) else RED)
        m.visual = trimesh.visual.ColorVisuals(m, face_colors=col)
        scene.add_geometry(m, node_name=f'{n}#{i}', geom_name=f'{n}#{i}')
        if not is_bone and base in LA and base not in seen and not SKIP.search(base) and (n.endswith('.r') or not re.search(r'\.(r|l)$', n)):
            seen.add(base); cen = m.vertices.mean(axis=0); v = m.vertices[np.argmin(np.linalg.norm(m.vertices - cen, axis=1))]
            la, uk = LA[base]; items.append({'n': len(items) + 1, 'la': la, 'uk': uk, 'pts': [[round((v[0] + 0.5) * 100, 2), round((0.5 - v[1]) * 100, 2)]], 'p3': [round(float(x), 4) for x in v]})
    out = f"glb/{S['id']}.glb"; scene.export(out); shutil.copy(out, A + f"models/{S['id']}.glb")
    missing = sorted({re.sub(r'\.(r|l)$', '', n) for n, _ in musc} - set(LA) - {x for x in LA})
    print(S['id'], os.path.getsize(out) // 1024, 'KB; meshes', len(musc), '+', len(bones), 'bones; pins', len(items), '; без назви:', [x for x in missing if not SKIP.search(x)][:12])
    out_sets.append({'id': S['id'], 'title': S['title'], 'cat': 'М’язи', 'file': f"models/{S['id']}.glb", 'model': True, 'w': 1000, 'h': 1000, 'items': items, 'topics': S['topics'],
        'credit': {'artist': 'Z-Anatomy (Lluís Vinent Juanico), за BodyParts3D', 'license': 'CC BY-SA 4.0', 'licurl': 'https://creativecommons.org/licenses/by-sa/4.0/', 'source': 'https://github.com/LluisV/Z-Anatomy'}})
json.dump(out_sets, open('sets3d_musc.json', 'w'), ensure_ascii=False, indent=1)
