"""3D-набори кісток кінцівок із Z-Anatomy: меші групи (права сторона) + маркери-підписи (.j), притягнуті до поверхні."""
import trimesh, numpy as np, json, re, os, shutil
A = '/Users/zxc/PycharmProjects/anat/'
SC = trimesh.load('SkeletalSystem100.glb', force='scene')
parent = {}
for e in SC.graph.to_edgelist(): parent[e[1]] = e[0]
def path(n):
    p = [n]
    while n in parent: n = parent[n]; p.append(n)
    return list(reversed(p))
base = lambda n: re.sub(r'_[0-9a-f]{6}$', '', n)

LA = {
 'Popliteal surface of femur':('Facies poplitea','Підколінна поверхня'),'Symphysial surface of pubis':('Facies symphysialis','Симфізна поверхня'),'Ischiopubic ramus':('Ramus ischiopubicus','Сідничо-лобкова гілка'),'Lunate surface':('Facies lunata','Півмісяцева поверхня'),'Sacropelvic surface of ilium':('Facies sacropelvica','Крижово-тазова поверхня'),'Supra-acetabular groove':('Sulcus supraacetabularis','Надкульшова борозна'),
 'Superior articular surface of lateral condyle':('Facies articularis superior (condylus lateralis)','Верхня суглобова поверхня бічного виростка'),'Superior articular surfaces of tibia':('Facies articularis superior tibiae','Верхня суглобова поверхня великогомілкової кістки'),'Tubercle of iliotibial tract':('Tuberculum tractus iliotibialis (Gerdy)','Горбок клубово-великогомілкового пасма'),
 'Base of phalanx of hand':('Basis phalangis','Основа фаланги'),'Body of phalanx of hand':('Corpus phalangis','Тіло фаланги'),'Head of phalanx of hand':('Caput phalangis','Головка фаланги'),'Trochlea of phalanx of hand':('Trochlea phalangis','Блок фаланги'),'Tuberosity of distal phalanx of hand':('Tuberositas phalangis distalis','Горбистість кінцевої фаланги'),'Body of metacarpal bone':('Corpus ossis metacarpi','Тіло п’ясткової кістки'),'Head of metacarpal bone':('Caput ossis metacarpi','Головка п’ясткової кістки'),'Metacarpal base':('Basis ossis metacarpi','Основа п’ясткової кістки'),
 'Base of metatarsal bone':('Basis ossis metatarsi','Основа плеснової кістки'),'Body of metatarsal bone':('Corpus ossis metatarsi','Тіло плеснової кістки'),'Head of metatarsal bone':('Caput ossis metatarsi','Головка плеснової кістки'),'Base of phalanx of foot':('Basis phalangis','Основа фаланги'),'Body of phalanx of foot':('Corpus phalangis','Тіло фаланги'),'Head of phalanx of foot':('Caput phalangis','Головка фаланги'),'Trochlea of phalanx of foot':('Trochlea phalangis','Блок фаланги'),'Tuberosity of distal phalanx of foot':('Tuberositas phalangis distalis','Горбистість кінцевої фаланги'),
 'Articular surface for cuboid':('Facies articularis cuboidea','Кубоподібна суглобова поверхня'),'Middle facet for calcaneus':('Facies articularis calcanea media','Середня п’яткова суглобова поверхня'),'Facet for plantar calcaneonavicular ligament':('Facies articularis ligamenti calcaneonavicularis plantaris','Поверхня для підошовної п’ятково-човноподібної зв’язки'),
 # плечова кістка
 'Anatomical neck of humerus':('Collum anatomicum','Анатомічна шийка'),'Anterior border of humerus':('Margo anterior','Передній край'),'Anterolateral surface of humerus':('Facies anterolateralis','Передньобічна поверхня'),'Anteromedial surface of humerus':('Facies anteromedialis','Передньоприсередня поверхня'),
 'Body of humerus':('Corpus humeri','Тіло плечової кістки'),'Capitulum of humerus':('Capitulum humeri','Головочка плечової кістки'),'Condyle of humerus':('Condylus humeri','Виросток плечової кістки'),'Coronoid fossa':('Fossa coronoidea','Вінцева ямка'),'Crest of greater tubercle':('Crista tuberculi majoris','Гребінь великого горбка'),
 'Crest of lesser tubercle':('Crista tuberculi minoris','Гребінь малого горбка'),'Deltoid tuberosity':('Tuberositas deltoidea','Дельтоподібна горбистість'),'Greater tubercle':('Tuberculum majus','Великий горбок'),'Groove for ulnar nerve':('Sulcus nervi ulnaris','Борозна ліктьового нерва'),'Head of humerus':('Caput humeri','Головка плечової кістки'),
 'Intertubercular sulcus':('Sulcus intertubercularis','Міжгорбкова борозна'),'Lateral border of humerus':('Margo lateralis','Бічний край'),'Lateral epicondyle of humerus':('Epicondylus lateralis','Бічний надвиросток'),'Lateral supracondylar ridge':('Crista supracondylaris lateralis','Бічний надвиростковий гребінь'),'Lesser tubercle':('Tuberculum minus','Малий горбок'),
 'Medial border of humerus':('Margo medialis','Присередній край'),'Medial epicondyle of humerus':('Epicondylus medialis','Присередній надвиросток'),'Medial supracondylar ridge':('Crista supracondylaris medialis','Присередній надвиростковий гребінь'),'Olecranon fossa':('Fossa olecrani','Ліктьова ямка'),'Posterior surface of humerus':('Facies posterior','Задня поверхня'),
 'Radial fossa':('Fossa radialis','Променева ямка'),'Radial groove':('Sulcus nervi radialis','Борозна променевого нерва'),'Surgical neck of humerus':('Collum chirurgicum','Хірургічна шийка'),'Trochlea of humerus':('Trochlea humeri','Блок плечової кістки'),
 # лопатка, ключиця
 'Acromial angle':('Angulus acromii','Кут надплечового відростка'),'Acromion':('Acromion','Надплечовий відросток'),'Clavicular facet':('Facies articularis clavicularis','Ключична суглобова поверхня'),'Coracoid process':('Processus coracoideus','Дзьобоподібний відросток'),'Costal surface of scapula':('Facies costalis','Реброва поверхня'),
 'Deltoid tubercle':('Tuberculum deltoideum','Дельтоподібний горбок'),'Glenoid fossa':('Cavitas glenoidalis','Суглобова западина'),'Glenoid process of scapula':('Collum scapulae (processus glenoidalis)','Суглобовий відросток'),'Inferior angle of scapula':('Angulus inferior','Нижній кут'),'Infraglenoid tubercle':('Tuberculum infraglenoidale','Підсуглобовий горбок'),
 'Infraspinous fossa':('Fossa infraspinata','Підостьова ямка'),'Lateral angle of scapula':('Angulus lateralis','Бічний кут'),'Lateral border of scapula':('Margo lateralis','Бічний край'),'Medial border of scapula':('Margo medialis','Присередній край'),'Neck of scapula':('Collum scapulae','Шийка лопатки'),
 'Posterior surface of scapula':('Facies posterior','Задня поверхня'),'Scapular notch':('Incisura scapulae','Вирізка лопатки'),'Spine of scapula':('Spina scapulae','Ость лопатки'),'Spinoglenoid notch':('Incisura spinoglenoidalis','Остьово-суглобова вирізка'),'Subscapular fossa':('Fossa subscapularis','Підлопаткова ямка'),
 'Superior angle of scapula':('Angulus superior','Верхній кут'),'Superior border of scapula':('Margo superior','Верхній край'),'Supraglenoid tubercle':('Tuberculum supraglenoidale','Надсуглобовий горбок'),'Supraspinous fossa':('Fossa supraspinata','Надостьова ямка'),
 'Acromial end':('Extremitas acromialis','Надплечовий кінець'),'Acromial facet':('Facies articularis acromialis','Надплечова суглобова поверхня'),'Body of clavicle':('Corpus claviculae','Тіло ключиці'),'Conoid tubercle':('Tuberculum conoideum','Конусоподібний горбок'),'Groove for subclavius muscle':('Sulcus musculi subclavii','Борозна підключичного м’яза'),
 'Impression for costoclavicular ligament':('Impressio ligamenti costoclavicularis','Втиснення реброво-ключичної зв’язки'),'Sternal articular surface':('Facies articularis sternalis','Груднинна суглобова поверхня'),'Sternal end':('Extremitas sternalis','Груднинний кінець'),'Trapezoid line':('Linea trapezoidea','Трапецієподібна лінія'),'Tuberosity for coracoclavicular ligament':('Tuberositas ligamenti coracoclavicularis','Горбистість дзьобо-ключичної зв’язки'),
 # променева, ліктьова
 'Anterior border of radius':('Margo anterior radii','Передній край променевої кістки'),'Anterior surface of radius':('Facies anterior radii','Передня поверхня променевої кістки'),'Articular circumference of head of radius':('Circumferentia articularis radii','Суглобовий обвід променевої кістки'),'Articular facet of head of radius':('Fovea articularis capitis radii','Суглобова ямка головки променевої кістки'),
 'Body of radius':('Corpus radii','Тіло променевої кістки'),'Carpal articular surface':('Facies articularis carpalis','Зап’ясткова суглобова поверхня'),'Dorsal radial tubercle':('Tuberculum dorsale radii','Тильний горбок променевої кістки'),'Grooves for extensor tendons':('Sulci tendinum musculorum extensorum','Борозни сухожилків м’язів-розгиначів'),'Head of radius':('Caput radii','Головка променевої кістки'),
 'Interosseous border of radius':('Margo interosseus radii','Міжкістковий край променевої кістки'),'Lateral surface of radius':('Facies lateralis radii','Бічна поверхня променевої кістки'),'Neck of radius':('Collum radii','Шийка променевої кістки'),'Posterior border of radius':('Margo posterior radii','Задній край променевої кістки'),'Posterior surface of radius':('Facies posterior radii','Задня поверхня променевої кістки'),
 'Pronator tuberosity':('Tuberositas pronatoria','Горбистість м’яза-привертача'),'Radial styloid process':('Processus styloideus radii','Шилоподібний відросток променевої кістки'),'Radial tuberosity':('Tuberositas radii','Горбистість променевої кістки'),'Suprastyloid crest':('Crista suprastyloidea','Надшилоподібний гребінь'),'Ulnar notch':('Incisura ulnaris','Ліктьова вирізка'),
 'Anterior border of ulna':('Margo anterior ulnae','Передній край ліктьової кістки'),'Articular circumference of head of ulna':('Circumferentia articularis ulnae','Суглобовий обвід ліктьової кістки'),'Body of ulna':('Corpus ulnae','Тіло ліктьової кістки'),'Coronoid process of ulna':('Processus coronoideus','Вінцевий відросток'),'Head of ulna':('Caput ulnae','Головка ліктьової кістки'),
 'Interosseous border of ulna':('Margo interosseus ulnae','Міжкістковий край ліктьової кістки'),'Medial surface of ulna':('Facies medialis ulnae','Присередня поверхня ліктьової кістки'),'Olecranon':('Olecranon','Ліктьовий відросток'),'Posterior border of ulna':('Margo posterior ulnae','Задній край ліктьової кістки'),'Posterior surface of ulna':('Facies posterior ulnae','Задня поверхня ліктьової кістки'),
 'Radial notch':('Incisura radialis','Променева вирізка'),'Sublime tubercle':('Tuberculum ulnae (sublime)','Горбок ліктьової кістки'),'Supinator crest':('Crista musculi supinatoris','Гребінь м’яза-відвертача'),'Trochlear notch':('Incisura trochlearis','Блокова вирізка'),'Tuberosity of ulna':('Tuberositas ulnae','Горбистість ліктьової кістки'),'Ulnar styloid process':('Processus styloideus ulnae','Шилоподібний відросток ліктьової кістки'),
 # кисть
 'Scaphoid bone':('Os scaphoideum','Човноподібна кістка'),'Lunate bone':('Os lunatum','Півмісяцева кістка'),'Triquetrum bone':('Os triquetrum','Тригранна кістка'),'Pisiform bone':('Os pisiforme','Горохоподібна кістка'),'Trapezium bone':('Os trapezium','Кістка-трапеція'),'Trapezoid bone':('Os trapezoideum','Трапецієподібна кістка'),'Capitate bone':('Os capitatum','Головчаста кістка'),'Hamate bone':('Os hamatum','Гачкувата кістка'),
 'First metacarpal bone':('Os metacarpi I','I п’ясткова кістка'),'Second metacarpal bone':('Os metacarpi II','II п’ясткова кістка'),'Third metacarpal bone':('Os metacarpi III','III п’ясткова кістка'),'Fourth metacarpal bone':('Os metacarpi IV','IV п’ясткова кістка'),'Fifth metacarpal bone':('Os metacarpi V','V п’ясткова кістка'),
 'Proximal phalanx of first finger of hand':('Phalanx proximalis pollicis','Проксимальна фаланга великого пальця'),'Distal phalanx of first finger of hand':('Phalanx distalis pollicis','Кінцева фаланга великого пальця'),
 'Proximal phalanx of second finger of hand':('Phalanx proximalis digiti II','Проксимальна фаланга II пальця'),'Middle phalanx of second finger of hand':('Phalanx media digiti II','Середня фаланга II пальця'),'Distal phalanx of second finger of hand':('Phalanx distalis digiti II','Кінцева фаланга II пальця'),
 'Proximal phalanx of third finger of hand':('Phalanx proximalis digiti III','Проксимальна фаланга III пальця'),'Middle phalanx of third finger of hand':('Phalanx media digiti III','Середня фаланга III пальця'),'Distal phalanx of third finger of hand':('Phalanx distalis digiti III','Кінцева фаланга III пальця'),
 'Proximal phalanx of fourth finger of hand':('Phalanx proximalis digiti IV','Проксимальна фаланга IV пальця'),'Middle phalanx of fourth finger of hand':('Phalanx media digiti IV','Середня фаланга IV пальця'),'Distal phalanx of fourth finger of hand':('Phalanx distalis digiti IV','Кінцева фаланга IV пальця'),
 'Proximal phalanx of fifth finger of hand':('Phalanx proximalis digiti V','Проксимальна фаланга V пальця'),'Middle phalanx of fifth finger of hand':('Phalanx media digiti V','Середня фаланга V пальця'),'Distal phalanx of fifth finger of hand':('Phalanx distalis digiti V','Кінцева фаланга V пальця'),
 'Hook of hamate bone':('Hamulus ossis hamati','Гачок гачкуватої кістки'),'Tubercle of scaphoid bone':('Tuberculum ossis scaphoidei','Горбок човноподібної кістки'),'Tubercle of trapezium bone':('Tuberculum ossis trapezii','Горбок кістки-трапеції'),'Styloid process of third metacarpal bone':('Processus styloideus ossis metacarpi III','Шилоподібний відросток III п’ясткової кістки'),
 # кульшова кістка
 'Acetabular fossa':('Fossa acetabuli','Ямка кульшової западини'),'Acetabular margin':('Limbus acetabuli','Край кульшової западини'),'Acetabular notch':('Incisura acetabuli','Вирізка кульшової западини'),'Acetabulum':('Acetabulum','Кульшова западина'),'Ala of ilium':('Ala ossis ilii','Крило клубової кістки'),
 'Anterior gluteal line':('Linea glutea anterior','Передня сіднична лінія'),'Anterior inferior iliac spine':('Spina iliaca anterior inferior','Нижня передня клубова ость'),'Anterior obturator tubercle':('Tuberculum obturatorium anterius','Передній затульний горбок'),'Anterior superior iliac spine':('Spina iliaca anterior superior','Верхня передня клубова ость'),'Arcuate line of ilium':('Linea arcuata','Дугоподібна лінія'),
 'Auricular surface of ilium':('Facies auricularis','Вушкоподібна поверхня'),'Body of ilium':('Corpus ossis ilii','Тіло клубової кістки'),'Body of ischium':('Corpus ossis ischii','Тіло сідничої кістки'),'Body of pubis':('Corpus ossis pubis','Тіло лобкової кістки'),'Gluteal surface of ilium':('Facies glutea','Сіднична поверхня'),
 'Greater sciatic foramen':('Foramen ischiadicum majus','Великий сідничий отвір'),'Greater sciatic notch':('Incisura ischiadica major','Велика сіднича вирізка'),'Iliac crest':('Crista iliaca','Клубовий гребінь'),'Iliac fossa':('Fossa iliaca','Клубова ямка'),'Iliac tubercle':('Tuberculum iliacum','Клубовий горбок'),
 'Iliac tuberosity':('Tuberositas iliaca','Клубова горбистість'),'Iliopubic eminence':('Eminentia iliopubica','Клубово-лобкове підвищення'),'Ilium':('Os ilium','Клубова кістка'),'Inferior gluteal line':('Linea glutea inferior','Нижня сіднична лінія'),'Inferior pubic ramus':('Ramus inferior ossis pubis','Нижня гілка лобкової кістки'),
 'Inner lip of iliac crest':('Labium internum cristae iliacae','Внутрішня губа клубового гребеня'),'Intermediate zone':('Linea intermedia','Проміжна лінія'),'Ischial spine':('Spina ischiadica','Сіднича ость'),'Ischial tuberosity':('Tuber ischiadicum','Сідничий горб'),'Ischium':('Os ischii','Сіднича кістка'),
 'Lesser sciatic foramen':('Foramen ischiadicum minus','Малий сідничий отвір'),'Lesser sciatic notch':('Incisura ischiadica minor','Мала сіднича вирізка'),'Lunate surface of acetabulum':('Facies lunata','Півмісяцева поверхня'),'Obturator crest':('Crista obturatoria','Затульний гребінь'),'Obturator foramen':('Foramen obturatum','Затульний отвір'),
 'Obturator groove':('Sulcus obturatorius','Затульна борозна'),'Outer lip of iliac crest':('Labium externum cristae iliacae','Зовнішня губа клубового гребеня'),'Pecten pubis':('Pecten ossis pubis','Гребінь лобкової кістки'),'Posterior gluteal line':('Linea glutea posterior','Задня сіднична лінія'),'Posterior inferior iliac spine':('Spina iliaca posterior inferior','Нижня задня клубова ость'),
 'Posterior superior iliac spine':('Spina iliaca posterior superior','Верхня задня клубова ость'),'Pubic crest':('Crista pubica','Лобковий гребінь'),'Pubic tubercle':('Tuberculum pubicum','Лобковий горбок'),'Pubis':('Os pubis','Лобкова кістка'),'Ramus of ischium':('Ramus ossis ischii','Гілка сідничої кістки'),
 'Superior pubic ramus':('Ramus superior ossis pubis','Верхня гілка лобкової кістки'),'Symphysial surface':('Facies symphysialis','Симфізна поверхня'),'Acetabular rim':('Limbus acetabuli','Край кульшової западини'),
 # стегнова кістка
 'Adductor tubercle':('Tuberculum adductorium','Привідний горбок'),'Body of femur':('Corpus femoris','Тіло стегнової кістки'),'Fovea for ligament of head of femur':('Fovea capitis femoris','Ямка головки стегнової кістки'),'Gluteal tuberosity':('Tuberositas glutea','Сіднична горбистість'),'Greater trochanter':('Trochanter major','Великий вертлюг'),
 'Groove for popliteus muscle':('Sulcus popliteus','Підколінна борозна'),'Head of femur':('Caput femoris','Головка стегнової кістки'),'Intercondylar fossa':('Fossa intercondylaris','Міжвиросткова ямка'),'Intercondylar line':('Linea intercondylaris','Міжвиросткова лінія'),'Intertrochanteric crest':('Crista intertrochanterica','Міжвертлюговий гребінь'),
 'Intertrochanteric line':('Linea intertrochanterica','Міжвертлюгова лінія'),'Lateral condyle of femur':('Condylus lateralis femoris','Бічний виросток стегнової кістки'),'Lateral epicondyle of femur':('Epicondylus lateralis femoris','Бічний надвиросток стегнової кістки'),'Lateral lip of linea apera':('Labium laterale lineae asperae','Бічна губа шорсткої лінії'),'Lateral supracondylar line':('Linea supracondylaris lateralis','Бічна надвиросткова лінія'),
 'Lesser trochanter':('Trochanter minor','Малий вертлюг'),'Linea aspera':('Linea aspera','Шорстка лінія'),'Medial condyle of femur':('Condylus medialis femoris','Присередній виросток стегнової кістки'),'Medial epicondyle of femur':('Epicondylus medialis femoris','Присередній надвиросток стегнової кістки'),'Medial lip of linea apera':('Labium mediale lineae asperae','Присередня губа шорсткої лінії'),
 'Medial supracondylar line':('Linea supracondylaris medialis','Присередня надвиросткова лінія'),'Neck of femur':('Collum femoris','Шийка стегнової кістки'),'Patellar surface of femur':('Facies patellaris','Наколінкова поверхня'),'Pectineal line of femur':('Linea pectinea','Гребінна лінія'),'Popliteal surface':('Facies poplitea','Підколінна поверхня'),
 'Trochanteric fossa':('Fossa trochanterica','Вертлюгова ямка'),'(Third trochanter)':('Trochanter tertius','Третій вертлюг'),'Quadrate tubercle':('Tuberculum quadratum','Квадратний горбок'),
 # гомілка
 'Anterior border of tibia':('Margo anterior tibiae','Передній край великогомілкової кістки'),'Anterior intercondylar area':('Area intercondylaris anterior','Переднє міжвиросткове поле'),'Articular facet of medial malleolus':('Facies articularis malleoli medialis','Суглобова поверхня присередньої кісточки'),'Articular surface of medial condyle':('Facies articularis superior (condylus medialis)','Верхня суглобова поверхня присереднього виростка'),
 'Body of tibia':('Corpus tibiae','Тіло великогомілкової кістки'),'Fibular articular facet':('Facies articularis fibularis','Малогомілкова суглобова поверхня'),'Fibular notch':('Incisura fibularis','Малогомілкова вирізка'),'Inferior articular surface of tibia':('Facies articularis inferior tibiae','Нижня суглобова поверхня'),'Intercondylar area':('Area intercondylaris','Міжвиросткове поле'),
 'Intercondylar eminence':('Eminentia intercondylaris','Міжвиросткове підвищення'),'Interosseous border of tibia':('Margo interosseus tibiae','Міжкістковий край великогомілкової кістки'),'Lateral condyle of tibia':('Condylus lateralis tibiae','Бічний виросток великогомілкової кістки'),'Lateral intercondylar tubercle':('Tuberculum intercondylare laterale','Бічний міжвиростковий горбок'),'Lateral surface of tibia':('Facies lateralis tibiae','Бічна поверхня великогомілкової кістки'),
 'Malleolar groove of tibia':('Sulcus malleolaris tibiae','Кісточкова борозна'),'Medial border of tibia':('Margo medialis tibiae','Присередній край великогомілкової кістки'),'Medial condyle of tibia':('Condylus medialis tibiae','Присередній виросток великогомілкової кістки'),'Medial intercondylar tubercle':('Tuberculum intercondylare mediale','Присередній міжвиростковий горбок'),'Medial malleolus':('Malleolus medialis','Присередня кісточка'),
 'Medial surface of tibia':('Facies medialis tibiae','Присередня поверхня великогомілкової кістки'),'Posterior intercondylar area':('Area intercondylaris posterior','Заднє міжвиросткове поле'),'Posterior malleolus':('Malleolus posterior','Задня кісточка'),'Posterior surface of tibia':('Facies posterior tibiae','Задня поверхня великогомілкової кістки'),'Soleal line':('Linea musculi solei','Лінія камбалоподібного м’яза'),
 'Superior articular surface of tibia':('Facies articularis superior tibiae','Верхня суглобова поверхня'),'Tibial tuberosity':('Tuberositas tibiae','Горбистість великогомілкової кістки'),'Tibial plateau':('Facies articularis superior tibiae','Суглобова поверхня (плато)'),
 'Anterior border of fibula':('Margo anterior fibulae','Передній край малогомілкової кістки'),'Anteromedial surface of fibula':('Facies medialis fibulae','Присередня поверхня малогомілкової кістки'),'Apex of head of fibula':('Apex capitis fibulae','Верхівка головки малогомілкової кістки'),'Articular facet of head of fibula':('Facies articularis capitis fibulae','Суглобова поверхня головки малогомілкової кістки'),'Articular facet of lateral malleolus':('Facies articularis malleoli lateralis','Суглобова поверхня бічної кісточки'),
 'Body of fibula':('Corpus fibulae','Тіло малогомілкової кістки'),'Head of fibula':('Caput fibulae','Головка малогомілкової кістки'),'Interosseous crest of fibula':('Margo interosseus fibulae','Міжкістковий край малогомілкової кістки'),'Lateral malleolus':('Malleolus lateralis','Бічна кісточка'),'Lateral surface of fibula':('Facies lateralis fibulae','Бічна поверхня малогомілкової кістки'),
 'Malleolar fossa':('Fossa malleoli lateralis','Ямка бічної кісточки'),'Malleolar groove of fibula':('Sulcus malleolaris fibulae','Кісточкова борозна малогомілкової кістки'),'Medial border of fibula':('Margo medialis fibulae','Присередній край малогомілкової кістки'),'Medial surface of fibula':('Facies medialis fibulae','Присередня поверхня малогомілкової кістки'),'Neck of fibula':('Collum fibulae','Шийка малогомілкової кістки'),
 'Posterior border of fibula':('Margo posterior fibulae','Задній край малогомілкової кістки'),'Posterior surface of fibula':('Facies posterior fibulae','Задня поверхня малогомілкової кістки'),'Posteromedial surface of fibula':('Facies posterior fibulae (pars medialis)','Задньоприсередня поверхня малогомілкової кістки'),
 # стопа
 'Calcaneus':('Calcaneus','П’яткова кістка'),'Talus':('Talus','Надп’яткова кістка'),'Navicular bone':('Os naviculare','Човноподібна кістка'),'Cuboid bone':('Os cuboideum','Кубоподібна кістка'),'Medial cuneiform bone':('Os cuneiforme mediale','Присередня клиноподібна кістка'),'Intermediate cuneiform bone':('Os cuneiforme intermedium','Проміжна клиноподібна кістка'),'Lateral cuneiform bone':('Os cuneiforme laterale','Бічна клиноподібна кістка'),
 'First metatarsal bone':('Os metatarsi I','I плеснова кістка'),'Second metatarsal bone':('Os metatarsi II','II плеснова кістка'),'Third metatarsal bone':('Os metatarsi III','III плеснова кістка'),'Fourth metatarsal bone':('Os metatarsi IV','IV плеснова кістка'),'Fifth metatarsal bone':('Os metatarsi V','V плеснова кістка'),'Sesamoid bones of foot':('Ossa sesamoidea','Сесамоподібні кістки'),
 'Proximal phalanx of first finger of foot':('Phalanx proximalis hallucis','Проксимальна фаланга великого пальця стопи'),'Distal phalanx of first finger of foot':('Phalanx distalis hallucis','Кінцева фаланга великого пальця стопи'),
 'Proximal phalanx of second finger of foot':('Phalanx proximalis digiti II pedis','Проксимальна фаланга II пальця стопи'),'Middle phalanx of second finger of foot':('Phalanx media digiti II pedis','Середня фаланга II пальця стопи'),'Distal phalanx of second finger of foot':('Phalanx distalis digiti II pedis','Кінцева фаланга II пальця стопи'),
 'Proximal phalanx of third finger of foot':('Phalanx proximalis digiti III pedis','Проксимальна фаланга III пальця стопи'),'Middle phalanx of third finger of foot':('Phalanx media digiti III pedis','Середня фаланга III пальця стопи'),'Distal phalanx of third finger of foot':('Phalanx distalis digiti III pedis','Кінцева фаланга III пальця стопи'),
 'Proximal phalanx of fourth finger of foot':('Phalanx proximalis digiti IV pedis','Проксимальна фаланга IV пальця стопи'),'Middle phalanx of fourth finger of foot':('Phalanx media digiti IV pedis','Середня фаланга IV пальця стопи'),'Distal phalanx of fourth finger of foot':('Phalanx distalis digiti IV pedis','Кінцева фаланга IV пальця стопи'),
 'Proximal phalanx of fifth finger of foot':('Phalanx proximalis digiti V pedis','Проксимальна фаланга V пальця стопи'),'Middle phalanx of fifth finger of foot':('Phalanx media digiti V pedis','Середня фаланга V пальця стопи'),'Distal phalanx of fifth finger of foot':('Phalanx distalis digiti V pedis','Кінцева фаланга V пальця стопи'),
 'Anterior process of calcaneus':('Processus anterior calcanei','Передній відросток п’яткової кістки'),'Calcaneal sulcus':('Sulcus calcanei','Борозна п’яткової кістки'),'Calcaneal tubercle':('Tuberculum calcanei','Горбок п’яткової кістки'),'Calcaneal tuberosity':('Tuber calcanei','Горб п’яткової кістки'),'Sustentaculum tali':('Sustentaculum tali','Підпора надп’яткової кістки'),
 'Lateral process of calcaneal tuberosity':('Processus lateralis tuberis calcanei','Бічний відросток горба п’яткової кістки'),'Medial process of calcaneal tuberosity':('Processus medialis tuberis calcanei','Присередній відросток горба п’яткової кістки'),'Posterior calcaneal articular facet':('Facies articularis talaris posterior','Задня суглобова поверхня п’яткової кістки'),'Groove for tendon of flexor hallucis longus of calcaneus':('Sulcus tendinis musculi flexoris hallucis longi (calcanei)','Борозна сухожилка довгого згинача великого пальця (п’яткова кістка)'),
 'Body of talus':('Corpus tali','Тіло надп’яткової кістки'),'Head of talus':('Caput tali','Головка надп’яткової кістки'),'Neck of talus':('Collum tali','Шийка надп’яткової кістки'),'Trochlea of talus':('Trochlea tali','Блок надп’яткової кістки'),'Superior facet of talus':('Facies superior trochleae tali','Верхня поверхня блока'),
 'Lateral malleolar facet':('Facies malleolaris lateralis','Бічна кісточкова поверхня'),'Medial malleolar facet':('Facies malleolaris medialis','Присередня кісточкова поверхня'),'Lateral process of talus':('Processus lateralis tali','Бічний відросток надп’яткової кістки'),'Posterior process of talus':('Processus posterior tali','Задній відросток надп’яткової кістки'),'Talar sulcus':('Sulcus tali','Борозна надп’яткової кістки'),
 'Tarsal sinus':('Sinus tarsi','Пазуха заплесна'),'Navicular articular surface':('Facies articularis navicularis','Човноподібна суглобова поверхня'),'Groove for tendon of flexor hallucis longus of talus':('Sulcus tendinis musculi flexoris hallucis longi (tali)','Борозна сухожилка довгого згинача великого пальця (надп’яткова кістка)'),'Lateral tubercle':('Tuberculum laterale processus posterioris tali','Бічний горбок заднього відростка'),'Medial tubercle':('Tuberculum mediale processus posterioris tali','Присередній горбок заднього відростка'),
 'Tuberosity of cuboid bone':('Tuberositas ossis cuboidei','Горбистість кубоподібної кістки'),'Tuberosity of navicular bone':('Tuberositas ossis navicularis','Горбистість човноподібної кістки'),'Groove for tendon of fibularis longus muscle of cuboid bone':('Sulcus tendinis musculi fibularis longi','Борозна сухожилка довгого малогомілкового м’яза'),'Tuberosity of fifth metatarsal bone':('Tuberositas ossis metatarsi V','Горбистість V плеснової кістки'),
}
SETS = [
 dict(id='v3-humerus', title='Плечова кістка — 3D', topic='m1:4', groups=['Humerus.r'], rel=['ul-113','ul-114','ul-115','ul-116']),
 dict(id='v3-scapula', title='Лопатка — 3D', topic='m1:4', groups=['Scapula.r'], rel=['ul-108','ul-109']),
 dict(id='v3-clavicle', title='Ключиця — 3D', topic='m1:4', groups=['Clavicle.r'], rel=[]),
 dict(id='v3-radius-ulna', title='Променева і ліктьова кістки — 3D', topic='m1:5', groups=['Radius.r','Ulna.r'], rel=['ul-121','ul-122','ul-123','ul-124','ul-125']),
 dict(id='v3-hand', title='Кістки кисті — 3D', topic='m1:5', groups=['Bones of free part of upper limb.g'], name_re=r'^(?!Humerus|Radius|Ulna).*\.r$', per_bone=True, rel=['hand-126','hand-127','hand-128','hand-129','hand-130','hand-131']),
 dict(id='v3-hip', title='Кульшова кістка — 3D', topic='m1:6', groups=['Hip bone.r'], rel=['ll-132','ll-133','ll-134','ll-135','ll-136']),
 dict(id='v3-femur', title='Стегнова кістка — 3D', topic='m1:6', groups=['Femur.r'], rel=['ll-137','ll-138','ll-139','ll-140','ll-141']),
 dict(id='v3-tibia-fibula', title='Великогомілкова і малогомілкова кістки — 3D', topic='m1:7', groups=['Tibia.r','Fibula.r'], rel=['ll-151','ll-152']),
 dict(id='v3-foot', title='Кістки стопи — 3D', topic='m1:7', groups=['Bones of foot.g'], name_re=r'\.r$', per_bone=True, rel=['ll-153','ll-154','ll-155','ll-156','ll-157']),
]
def proj(p): return [round((p[0]+0.5)*100,2), round((0.5-p[1])*100,2)]
os.makedirs('glb', exist_ok=True); out_sets = []
for S in SETS:
    meshes = []; markers = []
    for n in SC.graph.nodes_geometry:
        p = path(n); b = base(n)
        if not any(g in p for g in S['groups']): continue
        T, gname = SC.graph[n]; g = SC.geometry[gname]
        if n.endswith('.j'):
            markers.append((b[:-2], trimesh.transform_points(g.vertices, T).mean(axis=0))); continue
        if S.get('name_re') and not re.search(S['name_re'], b): continue
        if re.search(r'\.(o|e|e1)[rl]$|\.i$', b): continue      # ділянки початку/прикріплення м'язів
        m = g.copy(); m.apply_transform(T); meshes.append((b, m))
    allm = trimesh.util.concatenate([m for _, m in meshes]); c = allm.bounds.mean(axis=0); s = 1.0 / np.max(allm.extents)
    scene = trimesh.Scene(); items = []; seen = set()
    for i, (b, m) in enumerate(meshes):
        m.apply_translation(-c); m.apply_scale(s); m.merge_vertices(); m.visual = trimesh.visual.ColorVisuals(m, face_colors=[236, 229, 212, 255])
        scene.add_geometry(m, node_name=f'{b}#{i}', geom_name=f'{b}#{i}')
        if S.get('per_bone'):
            nm = re.sub(r'\.r$', '', b)
            if nm in LA and nm not in seen:
                seen.add(nm); cen = m.vertices.mean(axis=0); d = cen / (np.linalg.norm(cen) + 1e-9); v = m.vertices[np.argmax((m.vertices - cen) @ d)]
                la, uk = LA[nm]; items.append({'n': len(items) + 1, 'la': la, 'uk': uk, 'pts': [proj(v)], 'p3': [round(float(x), 4) for x in v]})
    whole = trimesh.util.concatenate([m for _, m in meshes])
    for nm, pt in markers:
        if nm not in LA or nm in seen: continue
        q = (np.asarray(pt) - c) * s
        (cp,), (dist,), _ = trimesh.proximity.closest_point(whole, [q])
        if dist > 0.08: continue                     # маркер іншої сторони / далеко від кістки
        seen.add(nm); la, uk = LA[nm]; items.append({'n': len(items) + 1, 'la': la, 'uk': uk, 'pts': [proj(cp)], 'p3': [round(float(x), 4) for x in cp]})
    out = f"glb/{S['id']}.glb"; scene.export(out); shutil.copy(out, A + f"models/{S['id']}.glb")
    missing = sorted({nm for nm, _ in markers if nm not in LA and not re.search(r'^(Humerus|Radius|Ulna|Scapula|Hip bone|Femur|Tibia|Fibula|Bones of|Tarsal bones|Metatarsal bones|Phalanges|Carpal|Metacarpal)', nm)})
    print(S['id'], os.path.getsize(out) // 1024, 'KB; meshes', len(meshes), 'items', len(items), '; без назви:', missing[:15])
    out_sets.append({'id': S['id'], 'title': S['title'], 'cat': 'Верхня кінцівка' if S['topic'] in ('m1:4', 'm1:5') else 'Нижня кінцівка', 'file': f"models/{S['id']}.glb", 'model': True, 'w': 1000, 'h': 1000, 'items': items, 'thumb': f"models/{S['id']}.jpg", 'rel2d': S['rel'][0] if S['rel'] else None, '_rel': S['rel'], '_topic': S['topic'],
        'credit': {'artist': 'Z-Anatomy (Lluís Vinent Juanico), за BodyParts3D', 'license': 'CC BY-SA 4.0', 'licurl': 'https://creativecommons.org/licenses/by-sa/4.0/', 'source': 'https://github.com/LluisV/Z-Anatomy'}})
json.dump(out_sets, open('sets3d_bones.json', 'w'), ensure_ascii=False, indent=1)
